### ISSUE TITLE
Detect disabling Auto Date/Time via Sync

### ISSUE THREAD

**Issue by danieleperilli** [sql-bi/Bravo#208]
### The feature request

If you’re using Auto Date/Time, Bravo says that Manage Dates is unsupported – fine. 
If I go back to my file, disable Auto Date/Time, Bravo is unable to detect the change: I have to close the report and reopen it to make the Manage Dates feature available.

### Proposed solution

Bravo should detect that Auto Date/Time has been disabled in the report when the Sync button is clicked.

**Comment by albertospelta** [comment]
Fixed in [0.9.1](https://github.com/sql-bi/Bravo/releases/tag/v0.9.1)
