### ISSUE TITLE
Add a button to analyze measures in Format DAX

### ISSUE THREAD

**Issue by danieleperilli** [sql-bi/Bravo#209]
### The feature request

When you open the Format DAX tab, it’s not immediately obvious how you can analyze measures. I.e. I see “7 to analyze”, and how do I analyze them? The “refresh” (Synchronize) button doesn’t do it.

### Proposed solution

Add a button to analyze the measures so that people don’t have to click around. Yes, I figured out you need to select a measure, then preview it, although it took some effort.

**Comment by albertospelta** [comment]
Fixed in [0.9.2](https://github.com/sql-bi/Bravo/releases/tag/v0.9.2)
