### ISSUE TITLE
Unclear error message in Manage Dates screen

### ISSUE THREAD

**Issue by DaanHumble** [sql-bi/Bravo#210]
### Describe the problem

When connected to a datamodel (the Contoso datamodel from the Tabular Modelling Course) this error message occurs in the Manage Dates screen:

![image](https://user-images.githubusercontent.com/41958563/160431426-c1e67571-201f-4485-a977-70a9931f7f25.png)

The error message does not provide any information on how to solve this. I'm also not sure of the cause of this problem, as I have a dedicated date table in the model..

### Bravo version

0.9.8121.26944

### Tabular model

Power BI Desktop, import mode

### Power BI

Version: 2.103.661.0 64-bit (March 2022)

### Steps to reproduce the behavior

- Connect to Contoso dataset 
- Go to Manage Dates
- Then the model check fails

### Screenshots

![image](https://user-images.githubusercontent.com/41958563/160431426-c1e67571-201f-4485-a977-70a9931f7f25.png)

**Comment by marcosqlbi** [comment]
Can you send us a copy of the model you used? This way we can try to reproduce.
Thanks!

**Comment by DaanHumble** [comment]
Ah, forgot to add that one. Here you go!

[Contoso.zip](https://github.com/sql-bi/Bravo/files/8364862/Contoso.zip)

**Comment by albertospelta** [comment]
Fixed in [0.9.1](https://github.com/sql-bi/Bravo/releases/tag/v0.9.1)
