### ISSUE TITLE
Bravo for Power BI - Internal Server Error

### ISSUE THREAD

**Issue by PEAKSvalleys** [sql-bi/Bravo#211]
Downloaded Bravo for Power BI and application was added into my External tools menu. Keep receiving the below error when I try to connect a Power BI workbook with Bravo. This error occurs if I try and connect from the external tool link within Desktop or by opening the app first and trying to connect to an open Power BI workbook.
---
Error HTTP/500: Internal Server Error.
Index was outside the bounds of the array.
Trace Id: 00-5be0a00064125549b3e236bc4f3295ed-c6c4065c5a66824f-00
Version: 0.9.0 (0.9.8121.26944)

**Comment by albertospelta** [comment]
@PEAKSvalleys, are you able to provide a version of the PBIX file that does not work? If you have sensitive data, try to copy the PBIX, remove the data you don't want to share, and try again to open it. When you have a version that still reproduces the problem and you can share, please send it to us. Thanks!

**Comment by albertospelta** [comment]
Fixed in [0.9.1](https://github.com/sql-bi/Bravo/releases/tag/v0.9.1)
