### ISSUE TITLE
Opening PBIX file: Object ref not set ...

### ISSUE THREAD

**Issue by rogerlight** [sql-bi/Bravo#213]
Go to Open --> Active Reports on power BI Desktop --> Browse. Select a PBIX file and get the error below. Other PBIX files are fine. The PBIX file with an error will open in PBI Desktop and will publish to the Service. 

---
Error HTTP/500: Internal Server Error.
Object reference not set to an instance of an object.
Trace Id: 00-4773cea16a714140ac5817d8f64f243b-4ba1e9b4b655cf4d-00
Version: 0.9.0 (0.9.8121.26944)

**Comment by marcosqlbi** [comment]
Are you able to provide a version of the PBIX file that does not work? If you have sensitive data, try to copy the PBIX, remove the data you don't want to share, and try again to open it. When you have a version that still reproduces the problem and you can share, please send it to us. Thanks!

**Comment by albertospelta** [comment]
Fixed in [0.9.1](https://github.com/sql-bi/Bravo/releases/tag/v0.9.1)
