### ISSUE TITLE
Expand All Button

### ISSUE THREAD

**Issue by darwinlloyd** [sql-bi/Bravo#214]
### The feature request

After the group by table, we have the option to Collapse all, but not the Expand all, it will be good to have that button as well as by default when we group by table is collapsing.

### Proposed solution

Please add Expand All

![image](https://user-images.githubusercontent.com/16768184/160445826-f50c001e-0d7f-4bf8-a71d-7bea57beafe1.png)

**Comment by albertospelta** [comment]
Fixed in [0.9.1](https://github.com/sql-bi/Bravo/releases/tag/v0.9.1)

**Comment by darwinlloyd** [comment]
Great, thank you
