### ISSUE TITLE
Cannot connect via XMLA if using Passwordless 2FA via Authenticator app

### ISSUE THREAD

**Issue by davideldersveld** [sql-bi/Bravo#215]
### Describe the problem

Attempting to Sign In to Power BI service. Using two factor auth with Microsoft's Authenticator app. Receive the prompt and number to confirm, enter it into Authenticator for approval, but Bravo then states that I need to use an alternative method to connect.

### Bravo version

0.9

### Tabular model

Power BI Dataset

### Power BI

Power BI Service

**Comment by albertospelta** [comment]
Can you provide a screenshot of the message displayed by Bravo? Does the account you used for authentication belong to the same Azure Active Directory tenant used by the Power BI service or does it belong to an external federated organization?

**Comment by albertospelta** [comment]
I'm not able to reproduce this issue but starting from the next release we will introduce an option to delegate the authentication flow to the OS default browser (system browser) instead of using the embedded authentication window.

**Comment by albertospelta** [comment]
Authentication via system browser was added in version [0.9.6](https://github.com/sql-bi/Bravo/releases/tag/v0.9.6)
If you’re still seeing issues, please feel free to post back here and we can reopen it.
