### ISSUE TITLE
Error 200: AS instance does not contain any databases

### ISSUE THREAD

**Issue by ihebcap** [sql-bi/Bravo#216]
Provide a detailed explanation of the issue in English.

---
Error 200: The Power BI Desktop Analysis Services instance does not contain any databases. Try to connect to the report using the Bravo icon in the External Tools of Power BI Desktop.
Version: 0.9.0 (0.9.8121.26944)

**Comment by marcosqlbi** [comment]
Can you describe the action you performed to see this error? Thanks!

**Comment by marcosqlbi** [comment]
The error explains what you are trying to do - did you try to connect Bravo to an empty PBIX file, or to a PBIX report connected to an external dataset?

**Comment by albertospelta** [comment]
This should be fixed with version [0.9.2](https://github.com/sql-bi/Bravo/releases/tag/v0.9.2), feel free to reopen if the issue still exists.
