### ISSUE TITLE
"Mal-formed string literal" format DAX error

### ISSUE THREAD

**Issue by AndreJaarconsult** [sql-bi/Bravo#217]
### Describe the problem

hi,
All measure that have html content inside is marked with errors.

### Bravo version

0.9.8121.26944

### Tabular model

Power BI Desktop, import mode

### Power BI

2.103.661.0 64-bit 

### Screenshots

![image](https://user-images.githubusercontent.com/59178334/160461218-54e78052-6504-45e6-ba29-0492c6431c9c.png)

**Comment by marcosqlbi** [comment]
Please, try again now - the problem was likely caused by multiple lines in the same literal strings, a syntax that was not supported by DAX Formatter because it has been introduced recently. It should be working now, otherwise please post the DAX code that doesn't work, thanks!

**Comment by AndreJaarconsult** [comment]
Working perfectly now
ty
