### ISSUE TITLE
Enable installation by non-administrator user

### ISSUE THREAD

**Issue by smearp** [sql-bi/Bravo#219]
### The feature request

Please add the ability to install as a user, without requiring local admin permissions, as DaxStudio/VS Code/etc do.

### Proposed solution

Users with locked-down work desktops will be able to install to their computer without having administrative priveleges.

**Comment by albertospelta** [comment]
Fixed in [0.9.2](https://github.com/sql-bi/Bravo/releases/tag/v0.9.2)
