### ISSUE TITLE
Error when Attach to PowerBI Desktop

### ISSUE THREAD

**Issue by aanyoti** [sql-bi/Bravo#221]
Hi, when attempting to attach to PowerBI Desktop I encounter this error, what could be the cause?

---
Error HTTP/500: Internal Server Error.
Object reference not set to an instance of an object.
Trace Id: 00-8ef0aca367ddb64a87de1b430988b28b-75b497ac7fcd8740-00
Version: 0.9.0 (0.9.8121.26944)

**Comment by albertospelta** [comment]
Closing this as duplicate #213

**Comment by albertospelta** [comment]
Fixed in [0.9.1](https://github.com/sql-bi/Bravo/releases/tag/v0.9.1)
