### ISSUE TITLE
Format string of Date column uses M or MM instead of the month number 

### ISSUE THREAD

**Issue by marcosqlbi** [sql-bi/Bravo#223]
### Describe the problem

The format string applied to the Date column of the Date table uses M instead of m.
This is caused by the .NET function ShortDatePattern that uses "M" for month number, whereas the format string of the column in Tabular requires "m" for month number.

### Bravo version

0.9.8121.26406

### Tabular model

Power BI Desktop, import mode

### Power BI

Power BI Desktop version March 2022

### Steps to reproduce the behavior

Create a Date table specifying a non-default regional format.

**Comment by albertospelta** [comment]
Fixed in [0.9.1](https://github.com/sql-bi/Bravo/releases/tag/v0.9.1)
