### ISSUE TITLE
Error HTTP/500: Internal Server Error.

### ISSUE THREAD

**Issue by fredfrota** [sql-bi/Bravo#224]
Error HTTP/500: Internal Server Error.
Object reference not set to an instance of an object.
Trace Id: 00-c9b3a6a709eb844c9f6bcd46c188f5c4-0fefa8a29fa4864f-00
Version: 0.9.0 (0.9.8121.26944)

**Comment by albertospelta** [comment]
Closing this as duplicate of #213

**Comment by albertospelta** [comment]
Fixed in [0.9.1](https://github.com/sql-bi/Bravo/releases/tag/v0.9.1)
