### ISSUE TITLE
DllNotFoundException: Unable to load DLL 'Photino.Native'

### ISSUE THREAD

**Issue by moen-cerix** [sql-bi/Bravo#225]
Running Power BI Desktop (Version: 2.103.661.0 64-bit (marts 2022)) using Parallels on Mac 

Downloaded and installed Bravo version 0.9.0 just fine, but when trying to launch Bravo via menu item "External tools", I receive the following error

<img width="559" alt="image" src="https://user-images.githubusercontent.com/102588342/160583051-03d11437-16c1-422d-aef9-54de14255a0f.png">

Errormessage: 

System.DllNotFoundException: Unable to load DLL 'Photino.Native' or one of its dependencies: Det angivne modul blev ikke fundet. (0x8007007E)
   at PhotinoNET.PhotinoWindow.Photino_register_win32(IntPtr hInstance)
   at PhotinoNET.PhotinoWindow.<>c.<.ctor>b__238_0()
   at PhotinoNET.PhotinoWindow.Invoke(Action workItem)
   at PhotinoNET.PhotinoWindow..ctor(PhotinoWindow parent)
   at Sqlbi.Bravo.Infrastructure.AppWindow.CreateWindow() in D:\a\1\s\src\Infrastructure\AppWindow.cs:line 58
   at Sqlbi.Bravo.Infrastructure.AppWindow..ctor(IHost host, AppInstance instance) in D:\a\1\s\src\Infrastructure\AppWindow.cs:line 35
   at Sqlbi.Bravo.Program.Main() in D:\a\1\s\src\Program.cs:line 25

**Comment by moen-cerix** [comment]
Issue replicated in issue #231   :)

**Comment by albertospelta** [comment]
Does the error only occur when launching Bravo via the Power BI external tools menu or even when launching Bravo.exe from the installation folder ? Which Windows OS build are you using ? 

Can you check whether the following files exist in the installation folder ? `C:\Program Files\SQLBI\Bravo\`  
- WebView2Loader.dll
- Photino.Native.dll
- Photino.NET.dll

**Comment by moen-cerix** [comment]
Hi

This is unfortunately both when opening Bravo from Power BI Desktop -> External Tools or lauching the bravo.exe directly.

I still get this error message:

System.DllNotFoundException: Unable to load DLL 'Photino.Native' or one of its dependencies: Det angivne modul blev ikke fundet. (0x8007007E)
   at PhotinoNET.PhotinoWindow.Photino_register_win32(IntPtr hInstance)
   at PhotinoNET.PhotinoWindow.<>c.<.ctor>b__238_0()
   at PhotinoNET.PhotinoWindow.Invoke(Action workItem)
   at PhotinoNET.PhotinoWindow..ctor(PhotinoWindow parent)
   at Sqlbi.Bravo.Infrastructure.AppWindow.CreateWindow() in D:\a\1\s\src\Infrastructure\AppWindow.cs:line 58
   at Sqlbi.Bravo.Infrastructure.AppWindow..ctor(IHost host, AppInstance instance) in D:\a\1\s\src\Infrastructure\AppWindow.cs:line 35
   at Sqlbi.Bravo.Program.Main() in D:\a\1\s\src\Program.cs:line 25


All dll files are located in installation folder.

I am running Windows 10 Pro, version 21H1, build 19043.1586 as a virtual OS in Parallels Desktop version 17.1.1 (build 51537) on an iMac.

 I have also tried uninstalling Bravo and reinstalling, but I get the same error after reinstalling.

Venlig hilsen / Best regards

Mogens Engmark // CeriX
IT Manager
(+45) 61700856


Fra: Alberto Spelta ***@***.***>
Dato: tirsdag, 29. marts 2022 kl. 20.30
Til: sql-bi/Bravo ***@***.***>
Cc: Mogens Engmark ***@***.***>, Author ***@***.***>
Emne: Re: [sql-bi/Bravo] Error launching Bravo 0.9.0 from Power BI Desktop (Issue #225)

Does the error only occur when launching Bravo via the Power BI external tools menu or even when launching Bravo.exe from the installation folder ? Which Windows OS build are you using ?

Can you check whether the following files exist in the installation folder ? C:\Program Files\SQLBI\Bravo\

  *   WebView2Loader.dll
  *   Photino.Native.dll
  *   Photino.NET.dll

**Comment by nsdevaraj** [comment]
> Does the error only occur when launching Bravo via the Power BI external tools menu or even when launching Bravo.exe from the installation folder ? Which Windows OS build are you using ?
> 
> Can you check whether the following files exist in the installation folder ? `C:\Program Files\SQLBI\Bravo\`
> 
> * WebView2Loader.dll
> * Photino.Native.dll
> * Photino.NET.dll
all those 3 files are available
<img width="619" alt="image" src="https://user-images.githubusercontent.com/274062/160815852-225a84c1-63c9-4f0a-ac6a-6444b1ac1e90.png">

**Comment by nsdevaraj** [comment]
It works perfect after installing https://aka.ms/vs/17/release/vc_redist.x64.exe

**Comment by albertospelta** [comment]
Fixed in [0.9.2](https://github.com/sql-bi/Bravo/releases/tag/v0.9.2)
