### ISSUE TITLE
Error 600: You are not connected to the Internet.

### ISSUE THREAD

**Issue by chrisnaz** [sql-bi/Bravo#227]
Trying to formate dax measure. And here below the error I had
---
Error 600: You are not connected to the Internet.
[TimedOut] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond. (www.daxformatter.com:443)
Trace Id: 00-3f3d42ed56c22042a22b3a4d512c4351-fd3b0560d6928f44-00
Version: 0.9.0 (0.9.8121.26944)

**Comment by albertospelta** [comment]
It seems to be a problem with the internet connection. Are you using Bravo from a corporate network behind a proxy server?
Is the [daxformatter.com](http://www.daxformatter.com:443/) website accessible via a standard web browser?

**Comment by albertospelta** [comment]
Proxy server support will be available with the next release (0.9.5), which should solve this issue (see https://github.com/sql-bi/Bravo/issues/385).

**Comment by albertospelta** [comment]
This should be fixed in version [0.9.5](https://github.com/sql-bi/Bravo/releases/tag/v0.9.5), feel free to reopen if the issue still persists
