### ISSUE TITLE
Error in DateAutoTemplate

### ISSUE THREAD

**Issue by Laura-GB** [sql-bi/Bravo#228]
### Describe the problem

Error in the DAX for DateAutoTemplate. Code works fine just shows an error in the DAX. Default calendar settings were selected. 

![image](https://user-images.githubusercontent.com/12954710/160585229-984f2c38-ecec-474f-8aaa-7a3bbb57c4ca.png)

### Bravo version

0.9.8121.26944

### Tabular model

Power BI Desktop, import mode

### Power BI

Power BI Desktop version April 2022

### Steps to reproduce the behavior

1. Manage Dates
2. Preview Changes
3. Apply Changes

**Comment by marcosqlbi** [comment]
This is a bug of Power BI Desktop, which displayed as an error what is a valid DAX syntax.
We need to keep that syntax for technical reasons related to the DaxTemplate library we use to generate the code.
We cannot fix the issue, Microsoft should do that (it has been already reported several weeks ago).
