### ISSUE TITLE
Error when connecting to desktop model 

### ISSUE THREAD

**Issue by Gossow** [sql-bi/Bravo#232]
Provide a detailed explanation of the issue in English.

---
Error HTTP/500: Internal Server Error.
Object reference not set to an instance of an object.
Trace Id: 00-553ca1dbc4a671469d985e327aa2bbbe-10ae21d2df734c42-00
Version: 0.9.0 (0.9.8121.26944)

**Comment by albertospelta** [comment]
Fixed in [0.9.1](https://github.com/sql-bi/Bravo/releases/tag/v0.9.1)
