### ISSUE TITLE
Provide a meaningful issue title

### ISSUE THREAD

**Issue by jcharlton3** [sql-bi/Bravo#237]
Provide a detailed explanation of the issue in English.

---
Error HTTP/500: Internal Server Error.
Object reference not set to an instance of an object.
Trace Id: 00-9ca23152b6d4204c9407977cad61f65d-6a8e6dbda0006e47-00
Version: 0.9.0 (0.9.8121.26944)

**Comment by albertospelta** [comment]
Thanks for reporting this. I'm closing this issue as duplicate of https://github.com/sql-bi/Bravo/issues/213

**Comment by albertospelta** [comment]
Fixed in [0.9.1](https://github.com/sql-bi/Bravo/releases/tag/v0.9.1)
