### ISSUE TITLE
Add a copy and edit button for the formatted pane

### ISSUE THREAD

**Issue by jgojiz** [sql-bi/Bravo#238]
### The feature request

Add a copy button for the formatted pane, and maybe an edit function, just like daxformatter.com

### Proposed solution

Faster edition and copy paste of DAX expressions to power bi models

### Additional context

![image](https://user-images.githubusercontent.com/61666332/160618456-de9ec843-c525-49d3-a9fd-cc14e58ee6f6.png)

**Comment by albertospelta** [comment]
Hi @jgojiz, 
a copy button of the DAX expression is already available in the context menu of the two panels.

![image](https://user-images.githubusercontent.com/1957788/161513826-1fc4eae9-4d79-4569-b703-08a260e29ef7.png)

We do not have plans to implement an editing function in Bravo, if you need such advanced options you should use other tools such as Tabular Editor.
