### ISSUE TITLE
Please change the locale_name in the FORMAT function to the correct one. ja-JP

### ISSUE THREAD

**Issue by TakeshiKagata** [sql-bi/Bravo#240]
### Describe the problem

In the DAX expression generated by "Manege Dates", the locale_name argument of the FORMAT function is incorrect.

It is "ja-JP", not "jp-JP".

### Bravo version

0.9.8121.26944

### Tabular model

Power BI Desktop, import mode

### Power BI

Power BI Desktop 2.103.881.0 64-bit (March 2022)

### Steps to reproduce the behavior

1. Select Regional format - "Japanese(Japan)"
2. Create Dates table

### Screenshots

Select model culture, [Japanese(Japan)]
![image](https://user-images.githubusercontent.com/45945615/160625032-24a3c69f-c0cf-49c1-97e7-84aec3010da0.png)

locale_name
![image](https://user-images.githubusercontent.com/45945615/160627860-e431dd23-1dfa-49ff-aa2f-b5480003d1da.png)

**Comment by danieleperilli** [comment]
Thanks for reporting it, I will be included in the next build, as a workaround you can choose Other and enter the correct culture code in the custom input box.

**Comment by albertospelta** [comment]
Fixed in [0.9.1](https://github.com/sql-bi/Bravo/releases/tag/v0.9.1)
