### ISSUE TITLE
Provide a meaningful issue title

### ISSUE THREAD

**Issue by moussa16035** [sql-bi/Bravo#244]
Provide a detailed explanation of the issue in English.

---
Error HTTP/500: Internal Server Error.
Object reference not set to an instance of an object.
Trace Id: 00-016f875c9faff545a438e1f97a2e3f6d-3371f741cb842b42-00
Version: 0.9.0 (0.9.8121.26944)

**Comment by danieleperilli** [comment]
Thanks for reporting this. I'm closing this issue as a duplicate of #213.

**Comment by albertospelta** [comment]
Fixed in [0.9.1](https://github.com/sql-bi/Bravo/releases/tag/v0.9.1)

**Comment by moussa16035** [comment]
***@***.***
Harlan Donato
President at Contoso, Ltd.

Phone: 462-835-2759
Mobile: 462-423-4718
Email: ***@***.***

5678 Washington Street
Houston, TX 88915

www.contoso.com

[Titre : LinkedIn - Description : image of LinkedIn icon]<http://linkedin.com/> [Titre : Twitter - Description : image of Twitter icon] <http://twitter.com/>  [Titre : google+ - Description : image of google+ icon] <http://google.com/>



De : Alberto Spelta ***@***.***>
Envoyé : mercredi 30 mars 2022 10:26
À : sql-bi/Bravo ***@***.***>
Cc : Moussa Bouguerra ***@***.***>; Author ***@***.***>
Objet : Re: [sql-bi/Bravo] HTTP/500: Object reference not set to an instance of an object. (Issue #244)


Fixed in 0.9.1<https://github.com/sql-bi/Bravo/releases/tag/v0.9.1>
