### ISSUE TITLE
Provide a meaningful issue title

### ISSUE THREAD

**Issue by nanonroses** [sql-bi/Bravo#245]
Provide a detailed explanation of the issue in English.

---
Error HTTP/500: Internal Server Error.
Object reference not set to an instance of an object.
Trace Id: 00-1797f3072674d242bba6f20586d27dba-041e2a6ff56eab4c-00
Version: 0.9.0 (0.9.8121.26944)

**Comment by danieleperilli** [comment]
Thanks for reporting this. I'm closing this issue as a duplicate of #213.

**Comment by albertospelta** [comment]
Fixed in [0.9.1](https://github.com/sql-bi/Bravo/releases/tag/v0.9.1)
