### ISSUE TITLE
Error 200 when opening a live connection to Azure Analysis Service

### ISSUE THREAD

**Issue by sqlenders** [sql-bi/Bravo#256]
### Describe the problem

Error 200: The Power BI Desktop Analysis Services instance does not contain any databases. Try to connect to the report using the Bravo icon in the External Tools of Power BI Desktop.

### Bravo version

0.9.1 (0.9.8124.15471)

### Tabular model

Power BI Desktop, import mode

### Power BI

Version: 2.103.881.0 64-bit (March 2022)

### Steps to reproduce the behavior

1. Create a new PBI report 
2. Get data from Azure | Azure Analysis Service Database
3. Connect asazure://westeurope.asazure.windows.net/someserver
4. Check "Connect live"
5. Optional Sign in 
6. Select a datamart
7. Build your report and so on 

### Additional context

Our dataset is pretty large (100 GB) and we are running is on Azure Analysis Service Standard S8.

**Comment by albertospelta** [comment]
Hi @sqlenders, this issue should be fixed with version [0.9.2](https://github.com/sql-bi/Bravo/releases/tag/v0.9.2)
