### ISSUE TITLE
Error HTTP/500: Object reference not set to an instance of an object

### ISSUE THREAD

**Issue by fjcamachoj** [sql-bi/Bravo#257]
Provide a detailed explanation of the issue in English.

---
Error HTTP/500: Internal Server Error.
Object reference not set to an instance of an object.
Trace Id: 00-3c3c73a44baef04ba6853c76d9d06f1f-3562becce53c0d42-00
Version: 0.9.0 (0.9.8121.26944)

**Comment by albertospelta** [comment]
Hi @fjcamachoj, this issue has been fixed in the latest version which you can download here [0.9.1](https://github.com/sql-bi/Bravo/releases/tag/v0.9.1)

**Comment by fjcamachoj** [comment]
Yes, I updated and it works perfectly!!! Great tool. Thanks
