### ISSUE TITLE
Synchronize button becomes "NOT AVAILABLE" due to "Save as" in PBI Desktop

### ISSUE THREAD

**Issue by marshal115** [sql-bi/Bravo#259]
If saving pbix, say "Demo_A.pbix" to another name, "Demo_B.pbix", while Bravo is running, the Synchronize icon will become "NOT AVAILABLE".  This issue can be resolved by clicking + icon and select the file of newly saved file but I wonder if it's possible not to leave the current window just like how you use DAX Studio, which connects with localhost and doesn't have this issue. 

It'd be great if by clicking the Synchronize icon, the display name on Bravo changes from "Demo_A" to "Demo_B" instantly after saving current file to "Demo_B.pbix". 

Thanks!

**Comment by albertospelta** [comment]
Fixed in [0.9.2](https://github.com/sql-bi/Bravo/releases/tag/v0.9.2)
