### ISSUE TITLE
Please provide support for sovereign clouds

### ISSUE THREAD

**Issue by Hikmer** [sql-bi/Bravo#263]
### The feature request

Just checked out your tool but the login seems to be fixed for only the Power BI commercial cloud.  Would be nice if you could allow connectivity to the Microsoft government clouds. https://docs.microsoft.com/en-us/power-bi/enterprise/service-govus-overview#sign-in-to-power-bi-for-us-government

### Proposed solution

Allow users to select their endpoint or use API to determine the cloud associated with the login user.

**Comment by albertospelta** [comment]
Hi @Hikmer, we have added this functionality in an experimental build which, in addition to Power BI commercial cloud, also allows you to connect to other environments associated with the login user. Unfortunately we only have access to the commercial cloud environment of Power BI, so we are not able to verify that it is working properly.

It would be great if you could test this and give us some feedback. You can download this build (portable version) [from here](https://bravorelease.blob.core.windows.net/bravo-internal/experimental/Bravo.0.9.3.x64-portable.zip) or clone and compile from [this branch](https://github.com/sql-bi/Bravo/tree/alberto/exp-issue-263) if you prefer to start from source code. Currently we do not have UI-side support for choosing the environmentt to connect to, so you need to specify this parameter in the configuration file `%LOCALAPPDATA%\Bravo\usersettings.json`

![image](https://user-images.githubusercontent.com/1957788/165312162-77411cd9-3993-4091-89b8-e67bed0bf347.png) 

In the example `"pbiEnvironment": 1` refers to the GermanCloud. The available values are those listed here https://github.com/sql-bi/Bravo/blob/alberto/exp-issue-263/src/Infrastructure/Models/PBICloud/PBICloudEnvironmentType.cs

**Comment by awatsky** [comment]
Hey @albertospelta,  I am not seeing the drop down and the build is not liking my e-mail address.

![image](https://user-images.githubusercontent.com/20262286/170063628-0e68155f-7bd9-4d00-9772-c2ca51ac3d2c.png)

**Comment by albertospelta** [comment]
@awatsky Does the diagnostic panel contain any errors ?  
After validating the e-mail address, in case there are no errors, messages similar to those below should appear.

![image](https://user-images.githubusercontent.com/1957788/170075314-6054c954-8ed2-42aa-b103-64409fcc7ea6.png)

**Comment by albertospelta** [comment]
@awatsky  I guess the 403 Forbidden error response came from your internal corporate proxy server which denies access to the global discovery endpoint for the PBI Commercial cloud `https://api.powerbi.com/` due to firewall/proxy policies. (more info here https://docs.microsoft.com/en-us/power-bi/enterprise/service-govus-overview#sign-in-to-power-bi-for-us-government).

If your account is configured for GCC, then I would expect access to GCC/GCCHigh endpoint to be allowed. Could you try running this Powershell script ? (just copy&paste in PowerShell ISE and enter your account email) 

```Powershell
$email = "your@email-address.com"

# PBI Commercial Cloud
Invoke-WebRequest -Method POST -Uri "https://api.powerbi.com/powerbi/globalservice/v202003/environments/discover?user=$($email)" -ErrorAction Continue
# PBI GCC Cloud
Invoke-WebRequest -Method POST -Uri "https://api.powerbigov.us/powerbi/globalservice/v202003/environments/discover?user=$($email)" -ErrorAction Continue
# PBI GCC High Cloud
Invoke-WebRequest -Method POST -Uri "https://app.high.powerbigov.us/powerbi/globalservice/v202003/environments/discover?user=$($email)" -ErrorAction Continue
```
Thanks!!

**Comment by awatsky** [comment]
`
StatusCode        : 200
StatusDescription : OK
Content           : {"environments":[{"cloudName":"USGovCloud","azureActiveDirectoryUri":"https://login.microsoftonline
                    .com","azureResourceManagerUri":"https://management.usgovcloudapi.net","azureResourceManagerAadReso
                    ur...
RawContent        : HTTP/1.1 200 OK
                    Pragma: no-cache
                    Transfer-Encoding: chunked
                    Strict-Transport-Security: max-age=31536000; includeSubDomains
                    X-Frame-Options: deny
                    X-Content-Type-Options: nosniff
                    RequestId: cdf26e...
Forms             : {}
Headers           : {[Pragma, no-cache], [Transfer-Encoding, chunked], [Strict-Transport-Security, max-age=31536000; 
                    includeSubDomains], [X-Frame-Options, deny]...}
Images            : {}
InputFields       : {}
Links             : {}
ParsedHtml        : mshtml.HTMLDocumentClass
RawContentLength  : 4922

StatusCode        : 200
StatusDescription : OK
Content           : {"environments":[{"cloudName":"USGovCloud","azureActiveDirectoryUri":"https://login.microsoftonline
                    .com","azureResourceManagerUri":"https://management.usgovcloudapi.net","azureResourceManagerAadReso
                    ur...
RawContent        : HTTP/1.1 200 OK
                    Pragma: no-cache
                    Transfer-Encoding: chunked
                    Strict-Transport-Security: max-age=31536000; includeSubDomains
                    X-Frame-Options: deny
                    X-Content-Type-Options: nosniff
                    RequestId: 3ab523...
Forms             : {}
Headers           : {[Pragma, no-cache], [Transfer-Encoding, chunked], [Strict-Transport-Security, max-age=31536000; 
                    includeSubDomains], [X-Frame-Options, deny]...}
Images            : {}
InputFields       : {}
Links             : {}
ParsedHtml        : mshtml.HTMLDocumentClass
RawContentLength  : 4922

StatusCode        : 200
StatusDescription : OK
Content           : 
                    <!DOCTYPE html>
                    <html xmlns="http://www.w3.org/1999/xhtml" >
                        <head>
                            <title>Power BI Error</title>
                            <meta http-equiv="X-UA-Compatible" content="IE=edge;" />
                    
                            <meta ch...
RawContent        : HTTP/1.1 200 OK
                    Strict-Transport-Security: max-age=31536000; includeSubDomains
                    Content-Length: 11857
                    Cache-Control: private
                    Content-Type: text/html; charset=utf-8
                    Set-Cookie: WFESessionId=87454cc...
Forms             : {}
Headers           : {[Strict-Transport-Security, max-age=31536000; includeSubDomains], [Content-Length, 11857], 
                    [Cache-Control, private], [Content-Type, text/html; charset=utf-8]...}
Images            : {@{innerHTML=; innerText=; outerHTML=<img src="13.0.18265.49/images/errors/owl_searching.png">; 
                    outerText=; tagName=IMG; src=13.0.18265.49/images/errors/owl_searching.png}}
InputFields       : {}
Links             : {@{innerHTML=Power BI; innerText=Power BI; outerHTML=<a class="powerBILogoText" href="/">Power 
                    BI</a>; outerText=Power BI; tagName=A; class=powerBILogoText; href=/}, @{innerHTML=Go back home; 
                    innerText=Go back home; outerHTML=<a class="continueLinkText" href="/" target="_blank">Go back 
                    home</a>; outerText=Go back home; tagName=A; class=continueLinkText; href=/; target=_blank}}
ParsedHtml        : mshtml.HTMLDocumentClass
RawContentLength  : 11857
`

**Comment by albertospelta** [comment]
Hi @awatsky, sorry for the late reply.  The `403 Forbidden` error most likely comes from the corporate proxy server. Is there any chance to run another test using an Internet connection that does not go through the proxy server? Thanks!
