### ISSUE TITLE
Manage Dates: 544 Calendar

### ISSUE THREAD

**Issue by vgeldbr** [sql-bi/Bravo#266]
I cannot get the 544 calendar configuration to work. Our financial calendar:

1. 544 week structure
2. Year runs July to June
3. Week ends on Friday
4. Fiscal year starts on Saturday
5. We name our fiscal year by the calendar year of the last date of the fiscal year (ie. July 2021 to June 2022 = Fiscal Year 2022)

When I try to configure this in Bravo the resulting Date table does not match.
1. Calendar Template = Weekly
2. Weekly System = 544
3. Fist Month of Year = July
4. First Day of the Week = Saturday
6. First Day of the Fiscal Year = First of the Year
7. Last Weekday of the Year = Last of the Year
8. Date Interval (First Year) = 2021
9. Date Interval (Last Year) = 2023
10. Regional Format = UK

![image](https://user-images.githubusercontent.com/55981045/161228227-9567d78c-2987-4495-b543-779841abeb40.png)

The resulting Date table starts on 29 May 2021 (one month too soon) and ends on 31 May 2024 (one month too soon).

**Comment by vgeldbr** [comment]
I installed latest, refreshed date table but I still see the incorrect (for us) Fiscal Year. It uses the year of the start date not the year of the end date in the fiscal year range..

**Comment by vgeldbr** [comment]
Actually @albertospelta , if I set Fist Day of the Fiscal Year to "Last day of the Year" then it seems to work. I guess it's not clear to me what the exact purpose of this setting is. It seems to fix this issue to use it but I'm not clear if it might have other purpose. The guidance text is not clear to me.

**Comment by marcosqlbi** [comment]
We should improve the documentation for this setting.

**Comment by marcosqlbi** [comment]
Documentation updated in both UI and https://docs.sqlbi.com/bravo/features/manage-dates/
