### ISSUE TITLE
Export fails if table has a calculated column with an error in its expression

### ISSUE THREAD

**Issue by dpesante** [sql-bi/Bravo#268]
### Describe the problem

Error HTTP/500: Internal Server Error.
The query referenced calculated column 'Approval History Cases'[Workflow Case Sub Category FOR Request Export] which does not hold any data because there is an error in its expression.

### Bravo version

0.9.1 (0.9.8124.15471)

### Tabular model

Power BI Desktop, import mode

### Power BI

Desktop - March 2022

### Anything else ?

Trace Id: 00-c094e9ce54c51d418729dc59a7b32389-16ca4a28adadb440-00

**Comment by albertospelta** [comment]
Fixed in [0.9.3](https://github.com/sql-bi/Bravo/releases/tag/v0.9.3)
