### ISSUE TITLE
Calendar template Monthly - One year off

### ISSUE THREAD

**Issue by LostInTheFlood** [sql-bi/Bravo#270]
I might be doing something wrong but the "Manage Date" generates a result that is one year plus. 2021 = 2022 etc.

 
![2022-04-01 16_32_48-Test - Power BI Desktop](https://user-images.githubusercontent.com/61800011/161284699-fbf4ce32-70f0-45ce-ad0e-d090f40fa01a.png)

**Comment by albertospelta** [comment]
Can you provide more detail on which 'Manage Date' template and settings have been used ?
A sample PBIX reproducing the problem would also be very useful.
Thanks!

**Comment by LostInTheFlood** [comment]
Hi
In the pptx I have highlighted the "settings" I did. The zip contains my sample pbix.
I'm probably just doing something incorrectly, but it's good to know what.

have a nice weekend.

[Bravo for Power BI.pptx](https://github.com/sql-bi/Bravo/files/8399463/Bravo.for.Power.BI.pptx)
[Test.zip](https://github.com/sql-bi/Bravo/files/8399470/Test.zip)

**Comment by marcosqlbi** [comment]
Bug fixed in DaxTemplate library, must be ported to Bravo.

**Comment by albertospelta** [comment]
Fixed in [0.9.3](https://github.com/sql-bi/Bravo/releases/tag/v0.9.3)
