### ISSUE TITLE
Update notifications must be translated

### ISSUE THREAD

**Issue by danieleperilli** [sql-bi/Bravo#275]
### Describe the problem

When a new version of Bravo is available, a system notification (toast) is displayed in English, regardless of the UI language.
It should match the UI language.

### Bravo version

0.9.1

### Tabular model

Power BI Desktop, import mode

### Power BI

Any

**Comment by albertospelta** [comment]
Added in version [0.9.5](https://github.com/sql-bi/Bravo/releases/tag/v0.9.5)
