### ISSUE TITLE
Reported table size query

### ISSUE THREAD

**Issue by MarkL76** [sql-bi/Bravo#286]
### Describe the problem

We have a large datamodel (60+ tables), but I was surprised to see that two date tables are being reported as the 2nd and 3rd largest tables with a size of 32MB and 23MB, yet they only contain 1,826 rows (5 years)?

I launch Bravo from External Tools immediately after opening my pbix.  I Then select ‘Group by Table’ and then clicked on the ‘Smaller columns’ option to include all tables in the view and the two date tables are still at the top:

![image](https://user-images.githubusercontent.com/44395864/161767133-e1fe6031-bbd9-4b97-a10a-c392cc31e32a.png)

![image](https://user-images.githubusercontent.com/44395864/161767184-59aa2ccc-26d0-4a87-a7e7-eb2eeb4c70e3.png)

Table ‘Dates’ is a DAX created table with some additional Y/N calculated columns and ‘Order Dates’ is simply a duplicate of Dates:

```
Dates = 
ADDCOLUMNS (
    CALENDAR ("2019-01-01", DATE(YEAR(TODAY())+1, 12, 31)),
    "Year", YEAR ( [Date] ),
    "DayNumber", DAY([Date]),
    "Monthnumber", MONTH([Date]),
    "YearMonthNo",  YEAR ( [Date] ) * 100 + MONTH([Date]),
    "YearMonthShort", FORMAT ( [Date], "YYYY mmm" ),
    "MMM-YY", FORMAT ( [Date], "mmm-YY" ),
    "MMM-YY Rev", FORMAT ( [Date], "mmm-YY" ),
    "Year-MonthNo", FORMAT([Date], "YYYY-MM"),
    "MonthNameShort", FORMAT ( [Date], "mmm" ),
    "Month", FORMAT ( [Date], "mmmm" ),
    "DayOfWeekNumber", WEEKDAY ( [Date],2 ),  
    "DayOfWeek", FORMAT ( [Date], "dddd" ),
    "DayOfWeekShort", FORMAT ( [Date], "ddd" ),
    "DayOfWeekLetter", LEFT(FORMAT([Date], "DDD"), 1), 
    "Quarter", "Q" & FORMAT ( [Date], "Q" ),
    "Quarternumber",QUARTER([Date]),
    "YearQuarterNo",  YEAR ( [Date] ) * 100 + QUARTER([Date]),
    "Week No", WEEKNUM([Date], 2),
    "Week No Rev", WEEKNUM([Date], 2),
    "Week Year", WEEKNUM([Date], 2) & "/" & FORMAT([Date], "YY"),
    "Week Year Rev", WEEKNUM([Date], 2) & "/" & FORMAT([Date], "YY"),
    "Week Year Sort",  YEAR ( [Date] ) * 100 + WEEKNUM([Date], 2),
    "Week Year Sort Rev",  999999 - (YEAR ( [Date] ) * 100) + (99 - WEEKNUM([Date], 2))
)

Order Dates = Dates

```

I’m really surprised to see that these two tables account for 55MB of our 275MB 60+ table model, with some of these tables containing 4M+ rows?

When I expand the tables in Bravo to see the fields, it is showing many fields which are Calculated columns containing just ‘Y’ or ‘N’ are all reported at 1.02MB each:

![image](https://user-images.githubusercontent.com/44395864/161767293-b5393a61-89e7-4e68-b63a-a6b8bb7452f8.png)

Do you think Bravo is getting something wrong here?   

Or are DAX created tables actually very heavy in size / memory?  If I drop the Results into Excel, the file is only 450kb.
 

### Bravo version

0.9.8124.15471

### Tabular model

Power BI Desktop, import mode

### Power BI

Version: 2.102.683.0 64-bit (February 2022)

### Steps to reproduce the behavior

1, Launch pbix
2, Launch Bravo from External Tools
3, Select ‘Group by Table’ 
4, Click on the ‘Smaller columns’ option to include all tables in the view.

**Comment by marcosqlbi** [comment]
I'm not able to replicate the issue.
Please, can you share a PBIX file that can reproduce the problem?

**Comment by MarkL76** [comment]
Hi Marco, unfortunately I cannot easily share due to content.  I would be happy to do a quick Teams / screenshare  to demonstrate through.

As a test I have deleted the 'Order Dates' table and the file size only dropped 45KB, whereas Bravo is reporting this table as 32.75MB (uncompressed?).

**Comment by daryl-lynch-bzy** [comment]
@MarkL76 , @albertospelta , @marcosqlbi - Would it be useful to attach the Vertipaq Analyser export from Dax Studio to compare against the results that you are seeing in Bravo.   It does make sense that the additional Calculated Columns with a "Y/N" value could take up that amount of space.  The single character string will be converted to HASH.  Maybe replacing Y/N will True/False will replace the String with Bit character.

**Comment by marcosqlbi** [comment]
@daryl-lynch-bzy Both Bravo and DAX Studio (and Tabular Editor) share the same VertiPaq Analyzer library. Indeed, you can export the same VPAX file.
Bravo provides a simplified view - you must use DAX Studio to get more details. This is by design and we do not want to bring all the features of DAX Studio in Bravo, we want to keep it (Bravo) simple.

**Comment by marcosqlbi** [comment]
I created a blog post to describe this behavior.
It is not an issue of Bravo, it is the way Power BI works. More details in this blog post:
https://www.sqlbi.com/blog/marco/2022/04/15/dictionary-size-in-tabular-models-reported-by-vertipaq-analyzer/
