### ISSUE TITLE
Cannot connect Bravo to Power BI

### ISSUE THREAD

**Issue by MateuszHydzik** [sql-bi/Bravo#292]
### Describe the problem

While connecting to Power BI Service i receive a message : "The XMLA endpoint is not supported for this dataset.".

While trying to open a report from my computer, Bravo opens the Power BI and the report but still shows the message "Waiting for file opening in Power BI Desktop...".
![image](https://user-images.githubusercontent.com/58403644/161968711-1c099f41-452f-4687-9d94-130953d3cd03.png)

When i open Bravo from External Tools tab in Power BI, report opens in Bravo app but it is named "Untitled", even though it has name, and shows only for a while and after 10 seconds an "NOT AVAILABLE" icon pops up.
![image](https://user-images.githubusercontent.com/58403644/161968984-dfaa629e-41b2-4fe4-9086-e3311cd62306.png)

### Bravo version

0.9.8130.24911

### Tabular model

Power BI Desktop, import mode

### Power BI

Power BI Desktop version March 2022

**Comment by albertospelta** [comment]
@MateuszHydzik, is your report connected to a Power BI Dataset or does it use a local model (import mode)?
Can you share a PBIX file that can reproduce the problem?
Thanks!

**Comment by MateuszHydzik** [comment]
> @MateuszHydzik, is your report connected to a Power BI Dataset or does it use a local model (import mode)? Can you share a PBIX file that can reproduce the problem? Thanks!

It uses a local model, but a report connected to a Power BI Dataset also does not respond.

**Comment by MateuszHydzik** [comment]
If i use the export data function they message does not appear. 
I guess i do not have a Power BI Premium plan...

Thank you in advance @albertospelta  !!
