### ISSUE TITLE
Calendar table in norwegian language

### ISSUE THREAD

**Issue by chairman2s** [sql-bi/Bravo#326]
### Describe the problem

When I select Norwegian (Norway) under Regional Format I get strange names for the weekdays and months but if I select Other... and then I correct `no_NO` under custom format to just `no` then the weekdays and months appear correctly. 

### Bravo version

0.9.3

### Tabular model

Power BI Desktop, import mode

### Power BI

Power BI Desktrop Version: 2.102.845.0 64-bit (februar 2022)

**Comment by albertospelta** [comment]
It's a bug, `no_NO` is a deprecated alias of `nb_NO` (Norwegian - Bokmål). 
Thanks for reporting!

**Comment by albertospelta** [comment]
Fixed in version [0.9.4](https://github.com/sql-bi/Bravo/releases/tag/v0.9.4)
