### ISSUE TITLE
Error 800: a table of multiple values supplied single value expected

### ISSUE THREAD

**Issue by Adriaanjac** [sql-bi/Bravo#330]
### Describe the problem

Hi there,

I cannot seem to generate a date table from my model this side.

I get the following error:

"Error 800: An Error occurred while executing DAX Template Engine. Query (581, 43) A table of multiple values was supplied where a single value was expected."

Does anyone know what can be the issue in my model?

### Bravo version

Version 0.9.8139.22766

### Tabular model

Power BI Desktop, import mode

### Power BI

Power BI Desktop version March 2022

### Screenshots

![2022-04-16_Image_660](https://user-images.githubusercontent.com/58063612/163686277-9b5642c2-7841-46e7-be2a-e7875976333c.png)
![2022-04-16_Image_661](https://user-images.githubusercontent.com/58063612/163686288-91a0c482-7314-4a0e-8353-904442254fdd.png)

**Comment by albertospelta** [comment]
Hi @Adriaanjac, thanks for reporting! This is probably a bug and not an issue in your model.
Could you share a minimal .pbix file that reproduces this behavior? Thanks!

**Comment by Adriaanjac** [comment]
Hi @albertospelta , I managed to sort out the issue. When I changed the Regional Format to English (United Kingdom) then it worked fine.

**Comment by albertospelta** [comment]
Thanks for this feedback @Adriaanjac!
- what is the active display language of your operating system ?
- What was the original regional format before you changed it to English (United Kingdom)? 
- could you share a minimal .pbix file that reproduces this ?

**Comment by marcosqlbi** [comment]
Probably fixed by #359

**Comment by albertospelta** [comment]
This should be fixed with version [0.9.4](https://github.com/sql-bi/Bravo/releases/tag/v0.9.4), feel free to reopen if the issue still persists.
