### ISSUE TITLE
Error 800: the syntax for 's' is incorrect

### ISSUE THREAD

**Issue by v-vivogt** [sql-bi/Bravo#336]
### Describe the problem

I'm trying to set up the calendar template using Bravo and keep receiving the Error 800 message. There isn't any direction on how to resolve this error. 

### Bravo version

0.9.8139.22766

### Tabular model

Power BI Desktop, import mode

### Power BI

2.100.1401.0 64-bit (December 2021)

### Steps to reproduce the behavior

1. Open Power BI desktop file
2. Click external tools
3. Click Bravo
4. Click Manage Dates
![bravo error](https://user-images.githubusercontent.com/103958610/163855254-464f2e7b-0f18-463f-9620-7953e9aa93f5.png)

**Comment by albertospelta** [comment]
Fixed in version [0.9.4](https://github.com/sql-bi/Bravo/releases/tag/v0.9.4)
