### ISSUE TITLE
Error HTTP/418: Operation aborted.

### ISSUE THREAD

**Issue by marahwa7d** [sql-bi/Bravo#341]
### Describe the problem

Error HTTP/418: Operation aborted.

### Bravo version

0.9.3 (0.9.8139.22766)

### Tabular model

Power BI Desktop, import mode

### Power BI

ower BI Desktop version

**Comment by albertospelta** [comment]
Hi @marahwa7d, I can't reproduce in my environment. 
Could you please provide more details or steps to reproduce the issue? Thanks

**Comment by marcosqlbi** [comment]
Closing the issue for lack of response.
