### ISSUE TITLE
Holidays Table 

### ISSUE THREAD

**Issue by aghonaim** [sql-bi/Bravo#347]
### The feature request

Since the "Holidays" table has a one to one relationship with the "Date" table, so it can be eliminated and  and add the "Holiday Name" column to the "Date" table. If it can't be eliminated  (for whatever reason), I suggest to add the relationship automatically between the "Date.Date" and "Holidays.Holiday Date" instead of adding it manually as it is now.     

### Proposed solution

Eliminate the "Holidays: table and add the "Holiday Name" column to the "Date" table. 
Or at least add the relationship automatically between the "Date.Date" and "Holidays.Holiday Date"

**Comment by marcosqlbi** [comment]
The current implementation of the template does not create a one-to-one relationship between Date and Holiday.
The Holidays table is used to decouple the stages where we create the holidays starting from the HolidaysDefinition table. It would be extremely complex to implement such a feature in the DAX code that generates the Date table, and the code would be hard to maintain. One of the goals is to generate code that can be maintained/replaced. For example, if you need to add/edit the Holidays table, you can still do that in DAX with minimal intervention in the current design.

However, I agree that the Holidays table should not be visible. **We must create the Holidays table as a hidden table** - currently, it is visible and it should not be. I keep the issue open to track this change

**Comment by aghonaim** [comment]
That makes sense now, thanks for the fix :)

**Comment by albertospelta** [comment]
Added in version [0.9.4](https://github.com/sql-bi/Bravo/releases/tag/v0.9.4)
