### ISSUE TITLE
An object with name '%' does not exist in the collection. (Parameter 'name')

### ISSUE THREAD

**Issue by DirkStorms** [sql-bi/Bravo#349]
### Describe the problem

Error HTTP/500: Internal Server Error.
 *** PLEASE REPORT THIS ISSUE ON GITHUB *** An object with name 'DateKey' does not exist in the collection. (Parameter 'name')

### Bravo version

0.9.3 (0.9.8139.22766)

### Tabular model

Power BI Desktop, import mode

### Power BI

Power Bi Desktop Version: 2.104.702.0 64-bit (April 2022)

### Anything else ?

Trace Id: 00-e7ea0a4672f08ecf1ee1164c3671928e-50e2b578bd8944ea-00

**Comment by albertospelta** [comment]
Hi @DirkStorms, thanks for filing the issue!
We are aware of this error but we need a minimum .pbix file that reproduces this behaviour. Can you provide this?

**Comment by albertospelta** [comment]
I am reopening this issue, we will close it as soon as the fix is released.

**Comment by albertospelta** [comment]
Fixed in version [0.9.4](https://github.com/sql-bi/Bravo/releases/tag/v0.9.4)
