### ISSUE TITLE
Calendar template layout error

### ISSUE THREAD

**Issue by lifeindarkside** [sql-bi/Bravo#355]
### Describe the problem

error in view element
![image](https://user-images.githubusercontent.com/66727826/164971344-c9ddeca7-ee16-45a5-86d5-36099a8a7cd6.png)

### Bravo version

0.9.8.8139.22766

### Tabular model

Power BI Desktop, import mode

### Power BI

Power BI Desktop version March 2022

### Steps to reproduce the behavior

1. connect to model
2. go to Manage dates
3. in Calendar tampleta box with "Standart" is whrong place.

Very important. Only with ru language

### Screenshots

![image](https://user-images.githubusercontent.com/66727826/164971548-734b2974-3d7c-446e-9b69-8443b7ba797f.png)

**Comment by albertospelta** [comment]
HI @lifeindarkside! It seems that your PR has fixed this issue 👍 
This is a screenshot from the internal build that contains your changes. 
![image](https://user-images.githubusercontent.com/1957788/164977345-52f34368-93de-4f05-b6fb-ef2219275c8e.png)
