### ISSUE TITLE
Error connecting to on-premises SSAS used in live connection

### ISSUE THREAD

**Issue by marcosqlbi** [sql-bi/Bravo#364]
### Describe the problem

Power BI has a live connection to a local SSAS database:
Error 200: The connection to the requested resource is not supported.

### Bravo version

0.9.3-internal-20220426.2-0.9.8151.17783-main-77ab64eb0cc62280d75cf731a972a61f1976bf17 (0.9.8151.17783)

### Tabular model

Power BI Desktop, import mode

### Power BI

Power BI Desktop version April 2022

### Steps to reproduce the behavior

1. Create a PBI Desktop file in Live connection to a local SSAS instance
2. Open Bravo from External Tools

**Comment by albertospelta** [comment]
@marcosqlbi can you check if the latest internal build solved the issue? Thanks.

**Comment by albertospelta** [comment]
Fixed in version [0.9.5](https://github.com/sql-bi/Bravo/releases/tag/v0.9.5)
