### ISSUE TITLE
Exporting measures 

### ISSUE THREAD

**Issue by Nithin211** [sql-bi/Bravo#367]
### The feature request

Please add a option to export measures to Excel. Or CSV so that it helps in documentation 

### Proposed solution

In formated DAX or Export data add this featured

**Comment by marcosqlbi** [comment]
You can already do that:

1. Use "Save as VPAX" in "Analyze Model"
2. Open the VPAX file with VertiPaq Analyzer, which is an Excel workbook that puts all the DAX expressions in a separate Excel table: https://www.sqlbi.com/tools/vertipaq-analyzer/
