### ISSUE TITLE
Mark some measures to exclude from Time Intelligence - 'permanently'

### ISSUE THREAD

**Issue by mscottsewell** [sql-bi/Bravo#373]
### The feature request

I can already manually 'uncheck' and prevent time intelligence measures from being created on some measures where they are not needed. (e.g. measures scoped to 'all dates')
However, the next time I open Bravo, I need to re-un-select all the same measures.
The ask is to allow me to somehow mark some measures as excluded, and persist that from session to session.

### Proposed solution

Avoid re-marking / accidentally creating time intelligence measures for measures where they are not needed or desired - from one bravo session to another.

**Comment by marcosqlbi** [comment]
@albertospelta could we include this selection in the configuration? Or is it already there and we ignore it?

**Comment by albertospelta** [comment]
@marcosqlbi This selection is currently not saved in the configuration but we can certainly add it.

**Comment by albertospelta** [comment]
Added in version [0.9.5](https://github.com/sql-bi/Bravo/releases/tag/v0.9.5)
