### ISSUE TITLE
Optionally create the Time Intelligence measure folders based on the measure name first.

### ISSUE THREAD

**Issue by mscottsewell** [sql-bi/Bravo#374]
### The feature request

Currently the time intelligence folder hierarchy is 
 \Time Intelligence
\ \TimeIntelligenceCategory
\ \ \MeasureFolder
\ \ \ \MeaureName
 \ \ \ \ \TimeIntelligenceMeasure

### Proposed solution

I'd like to drill through starting with the Measure Name (and Folder if available) and then (optionally to the measure category) and to the TI measure. 

\Time Intelligence
\ \MeasureFolder
\ \ \MeaureName
\ \ \ \TimeIntelligenceCategory (optional)
\ \ \ \ \TimeIntelligenceMeasure

**Comment by marcosqlbi** [comment]
This is already possible in the DaxTemplate library, but it is not exposed as a configuration in Bravo.
Would it be ok to customize the option in a JSON file?

**Comment by mscottsewell** [comment]
I suppose so - Let me look at the library.

**Comment by marcosqlbi** [comment]
@mscottsewell sorry for the delay - the documentation for the DAX Template library is available here: https://docs.sqlbi.com/dax-template/
In v1.0 it will be possible to edit these files and get the customized version in Bravo.

**Comment by albertospelta** [comment]
The ability to customize the Time Intelligence measure folders was added in version [0.9.6](https://github.com/sql-bi/Bravo/releases/tag/v0.9.6).

Using the template management panel on the Bravo options page it is now possible to clone an existing date template or create a new one from scratch. More information here:
- https://docs.sqlbi.com/bravo/options#templates 
- https://docs.sqlbi.com/bravo/customize-date-template.
