### ISSUE TITLE
A new version is available while the latest version is installed

### ISSUE THREAD

**Issue by NickyvVr** [sql-bi/Bravo#379]
### Describe the problem

I just downloaded the **0.9.3 Self contained - user** and after installing and opening Bravo, it immediately prompts for an update.
![image](https://user-images.githubusercontent.com/16239272/166458183-7f644bcc-642b-4f9e-bf80-d337b34c5b75.png)
But following that link still ends up at the same version: https://github.com/sql-bi/Bravo/releases.

### Bravo version

0.9.8139.22766

### Tabular model

Power BI Desktop, import mode

### Power BI

N/A

### Steps to reproduce the behavior

1. Download the latest version: https://github.com/sql-bi/Bravo/releases/download/v0.9.3/Bravo.0.9.3.x64-userinstaller.msi
2. Install it.
3. Open it.
4. It prompts with a "New version available".

**Comment by albertospelta** [comment]
You are right, we have just released version 0.9.4. The notification of the new version on GitHub takes a few minutes compared to the notification shown by the application, which is immediate.
