### ISSUE TITLE
Error connecting to dataset live connected to SSAS via PBI gateway

### ISSUE THREAD

**Issue by stuartmcnicholas** [sql-bi/Bravo#381]
### Describe the problem

Error HTTP/500: Internal Server Error.
The connection either timed out or was lost.

### Bravo version

0.9.1 (0.9.8124.15471)

### Tabular model

Power BI Dataset

### Power BI

Microsoft Analysis Services 14.0.3.441 (Power BI Gateway) 

### Screenshots

![image](https://user-images.githubusercontent.com/31472221/166573527-22776a1a-8bb3-4fae-8975-24a6256ccc4c.png)

### Anything else ?

Trace Id: 00-10c956913a263e4483584a2ad0695513-a99f41457fe19443-00

**Comment by albertospelta** [comment]
Hi @stuartmcnicholas, thanks for reporting! 
This is an issue we are aware of that has also been reported in #364 - we expect it to be fixed with the next release (v0.9.5)

**Comment by albertospelta** [comment]
This should be fixed in version [0.9.5](https://github.com/sql-bi/Bravo/releases/tag/v0.9.5), feel free to reopen if the issue still persists.
