### ISSUE TITLE
Fiscal year start issue

### ISSUE THREAD

**Issue by aghonaim** [sql-bi/Bravo#383]
### Describe the problem

The fiscal year is leading the calendar year while it should be lagging the calendar year.  
If I identify the starting month of my fiscal year to be on Apr the Date table is identifying the calendar Apr 2022 as the starting of the FY 2023 while it should be the starting month of  FY 2022.

### Bravo version

0.9.4

### Tabular model

Power BI Desktop, import mode

### Power BI

Power BI Desktop version Apr 2022

**Comment by marcosqlbi** [comment]
I don't understand the question - please, can you clarify with an example the current result and the expected one?

**Comment by aghonaim** [comment]
![Issue](https://user-images.githubusercontent.com/20173049/168190573-b4424600-91da-4a66-a909-97569c564249.JPG)

@marcosqlbi:  In this example,  for Jan-Mar 2007 (calendar), the fiscal year associated should be 2006 (Q4) and the starting of the FY 2007 should be in Apr 2007 calendar. 

Does this make sense now ?

**Comment by marcosqlbi** [comment]
Most companies do the opposite of what you are asking and identify the fiscal year with the year of the last day of the fiscal period. The Weekly calendar has a setting that controls this behavior: It is called "First Day of the Fiscal Year" in version 0.9.4 but we'll rename it in 0.9.5 (see #403).
Follow feature request #404 to see when this setting will be available in other templated (hopefully in 0.9.5).

**Comment by albertospelta** [comment]
Fixed in version [0.9.5](https://github.com/sql-bi/Bravo/releases/tag/v0.9.5)
