### ISSUE TITLE
Add setting to allow the input of proxy address and credentials

### ISSUE THREAD

**Issue by awatsky** [sql-bi/Bravo#385]
### The feature request

Currently there isn't a way to set a proxy address and credentials. As a result Format DAX will not work since my machine sends proxy tunnel requests. 

I am getting an error message (see below), but I think it is because Bravo doesn't currently have a way to connect to the proxy.

**Error message** 

```
Error HTTP/500: Internal Server Error.
The proxy tunnel request to proxy 'http://proxyaddress/' failed with status code '407'."
Trace Id: 00-8dc8694ddd2653f300edaa654c372a2d-5742497347e22f02-00
Version: 0.9.4 (0.9.8158.22794)
```
```{"name":"[HOST] UnhandledException","objects":["System.Net.Http.HttpRequestException: The proxy tunnel request to proxy 'http://proxyaddress/' failed with status code '407'.\"\r\n   at System.Net.Http.HttpConnectionPool.EstablishProxyTunnelAsync(Boolean async, HttpRequestHeaders headers, CancellationToken cancellationToken)\r\n   at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)\r\n   at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)\r\n   at System.Net.Http.HttpConnectionPool.AddHttp11ConnectionAsync(HttpRequestMessage request)\r\n   at System.Threading.Tasks.TaskCompletionSourceWithCancellation`1.WaitWithCancellationAsync(CancellationToken cancellationToken)\r\n   at System.Net.Http.HttpConnectionPool.GetHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)\r\n   at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)\r\n   at System.Net.Http.HttpConnectionPoolManager.SendAsyncMultiProxy(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, MultiProxy multiProxy, Uri firstProxy, CancellationToken cancellationToken)\r\n   at System.Net.Http.DiagnosticsHandler.SendAsyncCore(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)\r\n   at System.Net.Http.DecompressionHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)\r\n   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)\r\n   at Dax.Formatter.Client.Http.DaxFormatterHttpClient.<>c__DisplayClass15_0.<<GetServiceUriAsync>g__InitializeMultiServiceUriAsync|1>d.MoveNext()\r\n--- End of stack trace from previous location ---\r\n   at Dax.Formatter.Client.Http.DaxFormatterHttpClient.GetServiceUriAsync(DaxFormatterRequest request, CancellationToken cancellationToken)\r\n   at Dax.Formatter.Client.Http.DaxFormatterHttpClient.FormatImplAsync[T](T request, CancellationToken cancellationToken)\r\n   at Dax.Formatter.Client.Http.DaxFormatterHttpClient.FormatAsync(DaxFormatterMultipleRequest request, CancellationToken cancellationToken)\r\n   at Dax.Formatter.DaxFormatterClient.FormatAsync(DaxFormatterMultipleRequest request, CancellationToken cancellationToken)\r\n   at Sqlbi.Bravo.Services.FormatDaxService.CallDaxFormatterAsync(IEnumerable`1 measures, FormatDaxOptions options) in D:\\a\\1\\s\\src\\Services\\FormatDaxService.cs:line 124\r\n   at Sqlbi.Bravo.Services.FormatDaxService.FormatAsync(IEnumerable`1 measures, FormatDaxOptions options) in D:\\a\\1\\s\\src\\Services\\FormatDaxService.cs:line 39\r\n   at Sqlbi.Bravo.Controllers.FormatDaxController.Format(FormatDaxRequest request) in D:\\a\\1\\s\\src\\Controllers\\FormatDaxController.cs:line 51\r\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)\r\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)\r\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)\r\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)\r\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)\r\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)\r\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|25_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)\r\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)\r\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)\r\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)\r\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)\r\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)\r\n   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)\r\n   at Microsoft.AspNetCore.Authorization.Policy.AuthorizationMiddlewareResultHandler.HandleAsync(RequestDelegate next, HttpContext context, AuthorizationPolicy policy, PolicyAuthorizationResult authorizeResult)\r\n   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)\r\n   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)\r\n   at Hellang.Middleware.ProblemDetails.ProblemDetailsMiddleware.Invoke(HttpContext context)"],"time":1651703290687}```

### Proposed solution

Looking for the ability to input a proxy address and credentials similarly to how DAX Studio works. 

![image](https://user-images.githubusercontent.com/20262286/166837419-6d6fafe7-7076-4190-a334-196c6f74f820.png)

**Comment by albertospelta** [comment]
@awatsky Did the same error also occur when connecting to Power BI online datasets?

**Comment by awatsky** [comment]
@albertospelta Yes the same error occurs. I also tried via the External Tools panel and directly from Bravo when connecting to the dataset with no changes in results.

**Comment by albertospelta** [comment]
What proxy configuration do you use for DaxStudio? 
Do you only enable the "Use System Proxy" option only or do you enter the address and credentials?

**Comment by awatsky** [comment]
@albertospelta , I enter the address and credentials. 
![image](https://user-images.githubusercontent.com/20262286/166993668-4fb4600d-d37e-4825-84b2-ad4ec830ce29.png)
Currently, using System Proxy does not work. 
![image](https://user-images.githubusercontent.com/20262286/166993166-b40b8db6-ad00-4453-8e6c-06483e70eaab.png)

**Comment by albertospelta** [comment]
@awatsky we have an internal build available that introduces support for the proxy server., it would be great if you could test it and give us feedback. Please let me know so I can provide you with the download and configuration details. 
Thanks!

**Comment by awatsky** [comment]
@albertospelta absolutely!

**Comment by albertospelta** [comment]
@awatsky Sorry for the delay in replying, but we had to make other changes to fix minor issue in order to have a usable version for testing. You can now take the latest internal build by changing the release channel (from 'Stable' to 'Dev') in the configuration options. 

Once the new version is installed, authentication credentials must be added in the [Windows Credentials Manager](https://support.microsoft.com/en-us/windows/accessing-credential-manager-1b5c916a-6a16-889f-8581-fc16e8165ac0). Here the credential type to be selected is `Windows Credential` and the 'Internet or network address' parameter must have this value `Bravo for Power BI/proxy`.

![image](https://user-images.githubusercontent.com/1957788/167816344-d9172d98-e66e-4eb8-b883-62646cc8f5ed.png)

The next step is to add the proxy settings in the  `%LOCALAPPDATA%\Bravo\usersettings.json` file, as shown in the image below.

![image](https://user-images.githubusercontent.com/1957788/167818453-5659e35c-3be5-43c0-8776-9f95d9672783.png)

Here the value `proxy.type = 1` specifies that the OS's proxy configuration should be used, all supported options are [defined here](https://github.com/sql-bi/Bravo/blob/44c0a88993fc34c0588cb41272650fba2426a7a9/src/Infrastructure/Configuration/Settings/ProxySettings.cs#L78-L94)
```json
  "proxy": {
    "type": 1,
    "useDefaultCredentials": false,
    "address": null,
    "bypassOnLocal": true,
    "bypassList": null
  },
```
Starting the application should display a message similar to the one shown below in the Bravo diagnostic panel

![image](https://user-images.githubusercontent.com/1957788/167820262-349fd499-e260-488b-9c1f-f47b14879e07.png)

Please let me know if you have any questions or encounter any problems.
Thanks @awatsky  !

**Comment by awatsky** [comment]
@albertospelta is this something I can try with a portable version or my personal computer (one that does not use a proxy)? I ask because I do not have admin rights on my computer and will need my IT department to install the dev version. That can take some time.

**Comment by albertospelta** [comment]
@awatsky  You can download internal builds from here https://bravo.bi/builds.
Unser-installer and portable versions are also available.

**Comment by awatsky** [comment]
@albertospelta are there any other steps that I need to take?

**Comment by albertospelta** [comment]
In case of a HTTP/PROXY connection error, you should find the details in the diagnostic panel 
![image](https://user-images.githubusercontent.com/1957788/167892752-e8650656-e8b2-4d98-82e9-dbe7e380e809.png)

**Comment by awatsky** [comment]
> @awatsky The current version of Bravo only supports connection to the Power BI Commercial cloud service. For the connection to GCC and other PBI service environments we have an open issue here #263.
> 
> HTTP error `401 (Unauthorised)` could be generated either by the proxy server or by the Power BI service. We can try another test that does not involve authentication. In the settings panel we can check whether the application is able to connect to search for updates.
> 
> ![image](https://user-images.githubusercontent.com/1957788/167892332-ace63508-d750-4bf7-b4b7-bd09208c84e1.png)

I am able to check for updates.

![image](https://user-images.githubusercontent.com/20262286/167916580-ef3ef7de-62ba-4020-b6c3-e769a11579ee.png)

**Comment by albertospelta** [comment]
> So the 401 must be because Bravo is trying to authenticate against app.powerbi.com

I really think so

Just to double-check, if you change the password in the credentials manager by entering an incorrect one, do you receive the HTTP/401 error message when checking for updates?

**Comment by awatsky** [comment]
@albertospelta I just learned something. The proxy information inside the usersettings.json file is being overwritten after I modify the file with the default information. Once I have added all the information and save I go to open Bravo and instantly the file is overwritten to the default information. I set up everything as you explained, but I never tried using the formatter. Once I try using it I get the same error.

**Comment by albertospelta** [comment]
> The proxy information inside the usersettings.json file is being overwritten after I modify the file with the default information.

This probably happens because you are using `proxy.type = 1` in the configuration file `usersettings.json`, When `proxy.type = 1`, the OS conf  is used and the `proxy.address` value is reverted to the OS value.

If you restore the previous configuration, the one that allowed you to check for updates without errors, you should be able to use Bravo to connect to a PowerBI Desktop report and use the Bravo/Format DAX function. For this test PBIDesktop must have a local model (import mode) and not be connected to an online dataset.

**Comment by albertospelta** [comment]
@awatsky that's great news! Huge thanks for all the tests you did! 
Also great news is that it also works via auto-config proxy ( .PAC file in address )

**Comment by albertospelta** [comment]
@awatsky FYI, we just added (Dev channel only) support for proxy server configuration in the Bravo options panel. I am closing this issue, but feel free to reopen in case of further issues/questions. Thanks!

**Comment by albertospelta** [comment]
@awatsky FYI a new experimental build is available here https://github.com/sql-bi/Bravo/issues/263#issuecomment-1135751512 that supports authentication to GCC and other PBI environments. It would be great if you could test this and give us some feedback.
Thanks!

**Comment by albertospelta** [comment]
Added in version [0.9.5](https://github.com/sql-bi/Bravo/releases/tag/v0.9.5)
