### ISSUE TITLE
Add feature/regkey to block update notifications.

### ISSUE THREAD

**Issue by dragon687** [sql-bi/Bravo#396]
### The feature request

Can a feature be added to block the auto update notifications? 

### Proposed solution

Possibly make this a registry key similar to the telemetry disable options that already exist? Notifications can stay on for other general things, just looking for a way to disable the auto update check. 

### Additional context

This would be helpful for central IT departments deploying the application, that want to control which version is running on company machines.

**Comment by albertospelta** [comment]
@dragon687 Thanks for this suggestion, that's a good idea. I think we could use the registry key `HKLM\Software\Policies\SQLBI\Bravo` so it could also simplify the deployment via ADMX templates.
How does that sound?

**Comment by dragon687** [comment]
Sounds good to me! :)

**Comment by albertospelta** [comment]
Hi @dragon687, this feature will be available in the next release. 

`Software\Policies\SQLBI\Bravo\OptionSettings\UpdateCheckEnabled`, `REG_DWORD`, `1 = enabled`, `0 = disabled`

You can refer to the ADMX templates for full details 
https://github.com/sql-bi/Bravo/tree/main/src/Infrastructure/Security/Policies/ADMX

**Comment by dragon687** [comment]
Thanks a ton!

**Comment by albertospelta** [comment]
Added in version [0.9.5](https://github.com/sql-bi/Bravo/releases/tag/v0.9.5)
