### ISSUE TITLE
Add __TypeStartFiscalYear parameter in Monthly and Custom date templates

### ISSUE THREAD

**Issue by marcosqlbi** [sql-bi/Bravo#404]
### The feature request

Currently only the Weekly date templates has a __TypeStartFiscalYear parameter to control how to define the fiscal year number. 

### Proposed solution

The same setting should be ported to the other templates that have a Fiscal Year column.

**Comment by albertospelta** [comment]
Added in version [0.9.5](https://github.com/sql-bi/Bravo/releases/tag/v0.9.5)
