### ISSUE TITLE
First Day of Month missing

### ISSUE THREAD

**Issue by RofoRojas** [sql-bi/Bravo#406]
### Describe the problem

Error HTTP/500: Internal Server Error.
 *** PLEASE REPORT THIS ISSUE ON GITHUB *** La colección no contiene ningún objeto llamado 'Month Ref'. (Parameter 'name')

### Bravo version

0.9.4 (0.9.8158.22794)

### Tabular model

Power BI Dataset

### Power BI

Power BI Desktop version March 2022

### Steps to reproduce the behavior

So I added a custom made column on the dax that generates the date table, wich is just the first day of the month

### Additional context

I believe a  reference column like this is missing and on the final presentation it should be an option to hide it or not. 
This column wich is in reality a date but formated as "mm yyyy" should be available so it could be used as reference and to make visuals in time series continuos and not categorical.
I believe a column like that is missing on the calendar table and should be added. The option to have it hidden or not should be available in case the Fiscal Years are being used.

### Anything else ?

Trace Id: 00-038d4689ef1e155fe0a7901ef5c60fff-9bea84a4f374ef53-00

**Comment by albertospelta** [comment]
@RofoRojas thanks for reporting the issue!
Can you provide a sample PBIX file and the steps to reproduce this error?

**Comment by marcosqlbi** [comment]
Because we have many similar requests, we thought that the best way is to enable full customization of the template. This will not be done in the UI of Bravo to keep it simple and easy to use but through an external edit of the JSON configuration file. We should release that in v1.0.

**Comment by marcosqlbi** [comment]
The customization feature is already available in v0.9.6.
Documentation here: https://docs.sqlbi.com/bravo/features/manage-dates/customize-date-template
