### ISSUE TITLE
NullReferenceException raised instead of TOMDatabaseNotFound error

### ISSUE THREAD

**Issue by TheDanO** [sql-bi/Bravo#407]
### Describe the problem

Error happens when trying to connect to a report connecting to AAS. Login dialog shows, then shows this error.

Error HTTP/500: Internal Server Error.
Object reference not set to an instance of an object.
Trace Id: 00-4cd0e002bc13891b97eca4d15bc685bf-4ac9871c70517a2c-00
Version: 0.9.4-internal-20220515.1-0.9.8170.25813-main-2448ea4ea1f1bbccb2ec4aa32b28d274fc7a7e25 (0.9.8170.25813)

I have tried the stable version and the dev channel version.  Same result.

### Bravo version

0.9.4-internal-20220515.1-0.9.8170.25813-main-2448ea4ea1f1bbccb2ec4aa32b28d274fc7a7e25 (0.9.8170.25813)

### Tabular model

Power BI Dataset

### Power BI

Azure Analysis Services

**Comment by albertospelta** [comment]
@TheDanO thanks for reporting it! I just pushed a fix (#408) for an existing bug that was causing an incorrect error message to be displayed. The new build (0.9.8171.33978) is already available for download (dev channel only)

With this change, the expected error message should be _"The database does not exist in the collection or the user does not have administrator rights to access it."_.  

Does your account belong to a database role with administrator permissions ?

**Comment by TheDanO** [comment]
Yes it was the message that was throwing me off.  After update, I get the same message you have above. Would I need a higher permission for Bravo? PowerBI works against this AAS with my current permissions...

**Comment by albertospelta** [comment]
@TheDanO You are right, PowerBI works against AAS with your current permissions but allows you to only query the data. Bravo requires administrator permissions in order to access the advanced metadata of the model (for Analyze Model) and to be able to update the database schema (Format DAX)
