### ISSUE TITLE
Cannot Choose Measures for Time Intelligence

### ISSUE THREAD

**Issue by tjessome** [sql-bi/Bravo#423]
### Describe the problem

After adding date tables to a PBI Desktop model the ability to select specific measure to add time intelligence functions to is lost. When I initially added the date tables, I did not add any time intelligence functions.

### Bravo version

0.9.8158.22794

### Tabular model

Power BI Desktop, import mode

### Power BI

Version: 2.105.923.0 64-bit (May 2022)

**Comment by albertospelta** [comment]
@tjessome This error should be fixed in v0.9.5. Can you update the Bravo installation and try again?

**Comment by tjessome** [comment]
That worked. Thanks!
