### ISSUE TITLE
Windows Server 2016 not supported

### ISSUE THREAD

**Issue by R1k91** [sql-bi/Bravo#429]
### The feature request

Hi!

I've just updated my local Bravo installation to v0.9.4 but it turned out I cannot run it on my Windows Server 2016 VM.
v0.9.2 worked without any issue (installed through Power BI.tips' Business Ops Tool)

![image](https://user-images.githubusercontent.com/57228476/171222697-7159c37d-d51e-4e36-ad96-41578e3d5076.png)

is it a bug or you're not going to support that OS anymore?

thanks!

### Proposed solution

I know the majority of Power BI Users runs Power BI desktop on their clients that probably are Win10 machines, but there could be many cases where PBI desktop runs on shared RDPs or VMs running Windows Server OS.
In my case, as a consultant, I spin off VMs on my laptop to work with different customers and some of them could have Windows Server.

**Comment by albertospelta** [comment]
Ciao @R1k91, this limitation was introduced in version 0.9.3 but starting from the next release (0.9.5) compatibility will be extended to older versions of the Windows OS, for both client and server editions. The new version will be released in the next few days but in the meantime you can use the latest internal build - just change the update channel from 'stable' to 'dev' in the  options\about panel and follow the link to download the installer.

**Comment by R1k91** [comment]
Ciao @albertospelta great to hear that. thank you very much!

**Comment by albertospelta** [comment]
Added in version [0.9.5](https://github.com/sql-bi/Bravo/releases/tag/v0.9.5)
