### ISSUE TITLE
WebView2 Unable to cast COM object E_NOINTERFACE 0x80004002

### ISSUE THREAD

**Issue by emirtut** [sql-bi/Bravo#437]
### Describe the problem

portable version of Bravo 0.9.5x64 (from 04.06.2022, downloaded 06.06.2022) shows error during instalation as shown on enclosed picture.
I download portable version (zipped file and error is there). Even after I choose quite according to error, no Bravo is shown simple error
![Bravo 0 9 5 x64-portable_error](https://user-images.githubusercontent.com/69401624/172217721-85627402-d1af-43e6-8818-ddb1eda1abf5.png)

### Bravo version

Bravo.0.9.5.x64-portable.zip

### Tabular model

Power BI Desktop, import mode

### Power BI

May 2022 but not relevant since error is related to instalation

### Steps to reproduce the behavior

Simple instalation

### Additional context

I tried to install version 0.9.4 as it was working, still no success as message shows that I got newest version (but not working)

**Comment by albertospelta** [comment]
@emirtut thanks for reporting! 
In-place downgrade is not supported, the simpler method is to uninstall version v0.9.5 and then install v0.9.4. 

I have just pushed a fix for this issue, if you want to test it you can download the latest internal build here https://bravo.bi/builds
- portable version https://bravorelease.blob.core.windows.net/bravo-internal/2022/06/06/20220606.2-0.9.8192.36624/Bravo.0.9.5.x64-portable.zip
- installer version https://bravorelease.blob.core.windows.net/bravo-internal/2022/06/06/20220606.2-0.9.8192.36624/Bravo.0.9.5.x64.msi

Please let me know if this fixes the error, thanks!

**Comment by emirtut** [comment]
Hi Alberto,I am writing to you this way as on Github, I could not access the link to test update.This could last several days so if possible,  please plan release of updated version (my error version of Bravo) for first next release as I understand the bug is resolvedThank you,KrEmirDana 6. jun 2022. 22:50, osoba Alberto Spelta ***@***.***> je napisala:
@emirtut thanks for reporting!
In-place downgrade is not supported, the simpler method is to uninstall version v0.9.5 and then install v0.9.4.
I have just pushed a fix for this issue, if you want to test it you can download the latest internal build here https://bravo.bi/builds
portable version https://bravorelease.blob.core.windows.net/bravo-internal/2022/06/06/20220606.2-0.9.8192.36624/Bravo.0.9.5.x64-portable.zipinstaller version https://bravorelease.blob.core.windows.net/bravo-internal/2022/06/06/20220606.2-0.9.8192.36624/Bravo.0.9.5.x64.msi
Please let me know if this fixes the error, thanks!

**Comment by emirtut** [comment]
Hi Alberto,

I could not test installer version due to missing admin rights on my corporate machine.
For portable version, it seems the same error is there as before. Only difference I notice, is changed header name of error message - see yellow marked part on picture below.

Let me know what could be next step.

Kr
Emir

![portable version v0 9 5](https://user-images.githubusercontent.com/69401624/172997048-e43b2adc-2074-4537-98c6-1d956ae37b04.png)

**Comment by albertospelta** [comment]
Hi @emirtut, can you expand the detailed information by clicking the "Details" button and copy-paste here the content ? 

What is the version of the program "Microsoft Edge WebView2 Runtime" in the "Control Panel\Programs and Features" ?
![image](https://user-images.githubusercontent.com/1957788/173009857-8da6b01b-78a7-47ee-98d7-43eb9724b394.png)

Can you copy-paste here the Power BI Desktop session diagnostic content ? Button "Copy" in the "File\About" panel.
![image](https://user-images.githubusercontent.com/1957788/173011528-40f7f94a-d260-4ba4-9d89-90825f60cedf.png)

Thanks!

**Comment by emirtut** [comment]
Hi Alberto,

Below details. Part below Myuser is just dummy to hide real data

Also, picture of version below - older than yours.
![MicEdgeversion](https://user-images.githubusercontent.com/69401624/173030180-171ae6ee-faf6-48fb-aad1-7eeb70eaaa0d.png)

It could be that all this issues are related to my corporate setup so maybe I wrongly post bug. 
It will be create that somebody else confirm this version issues on my machine are only problems, not Bravo verision.

Thank you,

See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.InvalidCastException: Unable to cast COM object of type 'System.__ComObject' to interface type 'Microsoft.Web.WebView2.Core.Raw.ICoreWebView2Controller4'. This operation failed because the QueryInterface call on the COM component for the interface with IID '{97D418D5-A426-4E49-A151-E1A10F327D9E}' failed due to the following error: No such interface supported (0x80004002 (E_NOINTERFACE)).
   at Microsoft.Web.WebView2.Core.CoreWebView2Controller.get__nativeICoreWebView2Controller4()


************** Loaded Assemblies **************
System.Private.CoreLib
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.522.21309
    CodeBase: file:///D:/Users/Myuser/Downloads/Bravo.0.9.5.x64-portable/System.Private.CoreLib.dll
----------------------------------------
Bravo
    Assembly Version: 0.9.8192.36624
    Win32 Version: 0.9.8192.36624
    CodeBase: file:///D:/Users/Myuser/Downloads/Bravo.0.9.5.x64-portable/Bravo.dll
----------------------------------------
System.Runtime
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.522.21309
    CodeBase: file:///D:/Users/Myuser/Downloads/Bravo.0.9.5.x64-portable/System.Runtime.dll
----------------------------------------
Microsoft.Extensions.Hosting.Abstractions
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.21.52210
    CodeBase: file:///D:/Users/Myuser/Downloads/Bravo.0.9.5.x64-portable/Microsoft.Extensions.Hosting.Abstractions.dll
----------------------------------------
netstandard
    Assembly Version: 2.1.0.0
    Win32 Version: 6.0.522.21309
    CodeBase: file:///D:/Users/Myuser/Downloads/Bravo.0.9.5.x64-portable/netstandard.dll
----------------------------------------
System.Windows.Forms
    Assembly Version: 6.0.2.0
    Win32 Version: 6.0.422.16407
    CodeBase: file:///D:/Users/Myuser/Downloads/Bravo.0.9.5.x64-portable/System.Windows.Forms.dll
----------------------------------------
System.ComponentModel.Primitives
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.522.21309
    CodeBase: file:///D:/Users/Myuser/Downloads/Bravo.0.9.5.x64-portable/System.ComponentModel.Primitives.dll
----------------------------------------
System.Windows.Forms.Primitives
    Assembly Version: 6.0.2.0
    Win32 Version: 6.0.422.16407
    CodeBase: file:///D:/Users/Myuser/Downloads/Bravo.0.9.5.x64-portable/System.Windows.Forms.Primitives.dll
----------------------------------------
System.Runtime.InteropServices
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.522.21309
    CodeBase: file:///D:/Users/Myuser/Downloads/Bravo.0.9.5.x64-portable/System.Runtime.InteropServices.dll
----------------------------------------
System.Drawing.Primitives
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.522.21309
    CodeBase: file:///D:/Users/Myuser/Downloads/Bravo.0.9.5.x64-portable/System.Drawing.Primitives.dll
----------------------------------------
System.Collections.Specialized
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.522.21309
    CodeBase: file:///D:/Users/Myuser/Downloads/Bravo.0.9.5.x64-portable/System.Collections.Specialized.dll
----------------------------------------
System.Threading
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.522.21309
    CodeBase: file:///D:/Users/Myuser/Downloads/Bravo.0.9.5.x64-portable/System.Threading.dll
----------------------------------------
System.Diagnostics.TraceSource
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.522.21309
    CodeBase: file:///D:/Users/Myuser/Downloads/Bravo.0.9.5.x64-portable/System.Diagnostics.TraceSource.dll
----------------------------------------
System.Collections
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.522.21309
    CodeBase: file:///D:/Users/Myuser/Downloads/Bravo.0.9.5.x64-portable/System.Collections.dll
----------------------------------------
System.Drawing.Common
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.422.16404
    CodeBase: file:///D:/Users/Myuser/Downloads/Bravo.0.9.5.x64-portable/System.Drawing.Common.dll
----------------------------------------
System.Net.Primitives
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.522.21309
    CodeBase: file:///D:/Users/Myuser/Downloads/Bravo.0.9.5.x64-portable/System.Net.Primitives.dll
----------------------------------------
System.Private.Uri
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.522.21309
    CodeBase: file:///D:/Users/Myuser/Downloads/Bravo.0.9.5.x64-portable/System.Private.Uri.dll
----------------------------------------
System.Net.Http
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.522.21309
    CodeBase: file:///D:/Users/Myuser/Downloads/Bravo.0.9.5.x64-portable/System.Net.Http.dll
----------------------------------------
System.Diagnostics.Tracing
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.522.21309
    CodeBase: file:///D:/Users/Myuser/Downloads/Bravo.0.9.5.x64-portable/System.Diagnostics.Tracing.dll
----------------------------------------
System.Collections.Concurrent
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.522.21309
    CodeBase: file:///D:/Users/Myuser/Downloads/Bravo.0.9.5.x64-portable/System.Collections.Concurrent.dll
----------------------------------------
System.Diagnostics.Process
    Assembly Version: 6.0.0.0

**Comment by albertospelta** [comment]
Here the WebView2 opened issue https://github.com/MicrosoftEdge/WebView2Feedback/issues/2517

**Comment by albertospelta** [comment]
@emirtut I was finally able to reproduce the error. 
The latest internal build (0.9.8198.23921) here https://bravo.bi/builds should fix the error. 
Please let me know if you can run a test and if the error is resolved. 
Thanks!

- portable version https://bravorelease.blob.core.windows.net/bravo-internal/2022/06/12/20220612.1-0.9.8198.23921/Bravo.0.9.5.x64.msi
- installer version https://bravorelease.blob.core.windows.net/bravo-internal/2022/06/12/20220612.1-0.9.8198.23921/Bravo.0.9.5.x64-portable.zip

**Comment by emirtut** [comment]
Hi Alberto,

I could not test installer version due to missing admin rights on my corporate machine.
For portable version, the latest internal build (0.9.8198.23921) , seems ok now.

Thank you for support,

Let me know what could be next step: should we close this bug ID given that I do not have admin rights to test installer version?

Kr
Emir

**Comment by albertospelta** [comment]
@emirtut thanks to you too! I am closing this issue as Microsoft released a fix for this.
These changes will be included in the next release (v0.9.6)

> Here the WebView2 opened issue [MicrosoftEdge/WebView2Feedback#2517](https://github.com/MicrosoftEdge/WebView2Feedback/issues/2517)

**Comment by albertospelta** [comment]
Fixed in version [0.9.6](https://github.com/sql-bi/Bravo/releases/tag/v0.9.6)
