### ISSUE TITLE
Duplicate drop down items in Manage Dates - Calendar - Calendar Template ( Standard, Monthly ...)

### ISSUE THREAD

**Issue by adamsmodi** [sql-bi/Bravo#443]
### Describe the problem

Dear SQLBI Team,

I figured out something recently which might be a small issue when I test the "Manage Dates" function with Bravo.

I open Bravo via "External Tool" tab in Power BI, go to "Manage Dates" --> "Calendar" --> "Calendar Template" .
I expand the drop down menu, I see 4 options: Standard, Monthly, Custom, Weekly. 
I select Standard for example, then Preview Changes and apply it.  Everything is fine..

Then I don't close Bravo, I go to my Power BI and realize that "Standard" might not be the ideal calendar and I want to change it.
I go back to Bravo UI( which I never close after 1st deployment ), I try again to open the drop down menu of "Calendar Template". Then I will see 5 options: Two times "Standard", and Monthly, Custom, Weekly.

It seems that no matter which option I choose at the very begining, this option will be dulplicated in the drop down menu of "Calendar Template" when I try to change it second time. Save and close Power BI and Bravo and reopen them again won't solve this issue. I still see duplicated items in the drop down menu.

This is not a very big issue because as end user we can still understand.. But in my opinion, dulplicated options in drop down menu is redundant and should be avoid..

thanks 

### Bravo version

0.9.5-internal-20220612.1-0.9.8198.23921-main-c046b954ac48db360a634484dd574ffd5af58883 (0.9.8198.23921)

### Tabular model

Power BI Desktop, import mode

### Power BI

2.105.1143.0 64-bit (2022.05)

### Steps to reproduce the behavior

1st time
1. Go to "Manage Dates" --> "Calendar" --> "Calendar Template" 
2. Drop down menu  "Calendar Template"  Select "Standard"
3. Click "Preview Changes"
4. Click "Apply Changes"
Everything is fine
Don't close Bravo after 1st time apply changes.

Then we realize that "Standard" is not the right calendar we need. 
we want to change

2nd time ( Bravo keeps open all the time )
1. Go to "Manage Dates" --> "Calendar" --> "Calendar Template" 
2. Drop down menu  "Calendar Template"  Then I see the "Standard" option will be duplicated. I have 5 options in the dropdown menu.

### Additional context

German, English, Chinese Version have this issue. Other language not tested. 

### Screenshots

![图片](https://user-images.githubusercontent.com/51952216/174117776-640375ab-cba7-4098-93c5-74e95857ba5a.png)

**Comment by albertospelta** [comment]
@adamsmodi Thanks for reporting this! 
The duplicate option is added to the list of options after the template has been applied and represents a "virtual" template created from the applied configuration. This allows you to change the configuration of a previous applied template without having to configure it from scratch. The name of this option should definitely be different, e.g. "Standard (Current)", where "Standard" is the applied template name.

**Comment by adamsmodi** [comment]
> @adamsmodi Thanks for reporting this! The duplicate option is added to the list of options after the template has been applied and represents a "virtual" template created from the applied configuration. This allows you to change the configuration of a previous applied template without having to configure it from scratch. The name of this option should definitely be different, e.g. "Standard (Current)", where "Standard" is the applied template name.

@albertospelta thanks a lot for detailed explanation and it helps me to understand the intended configurations. This will definitely help if we change it with different name. 

I would even make it a little bit more clear. For example, when the user want to change calender template the 2nd time, the drop down menu could be "Standard(New)", "Standard(Current)", "Monthly", "Weekly", "Custom"

"Standard(New)" means create Standard template from scratch.
"Standard(Current)" means adjust the current applied template.

Just my personal preference for your information. I would also accept that we keep "Standard" in the context and just add "Standard(Current)" as new option. 

thanks a lot and wish you a nice day.

**Comment by albertospelta** [comment]
Added in version [0.9.6](https://github.com/sql-bi/Bravo/releases/tag/v0.9.6)

The template current applied has the suffix "(Current)" and is no longer duplicated 

![image](https://user-images.githubusercontent.com/1957788/189928932-438126a1-83df-453d-92fb-4acb8e1edda5.png)
