### ISSUE TITLE
unable to launch external tool/ Bravo

### ISSUE THREAD

**Issue by Ggithub2020** [sql-bi/Bravo#449]
### The feature request

Bravo executable not found. contact the tool author for support.

### Proposed solution

the external tool should be accessible with installer in SQLBI -tools .

### Additional context

![image](https://user-images.githubusercontent.com/73087775/174727750-d73caa97-0623-4bdb-a60b-427dfc17e627.png)

**Comment by albertospelta** [comment]
@Ggithub2020 Can you share the content of this file ?
`C:\Program Files (x86)\Common Files\Microsoft Shared\Power BI Desktop\External Tools\bravo.pbitool.json`

It should look something like this:
``` json
{
  "version": "1.0",
  "name": "Bravo",
  "description": "TODO",
  "path": "C:\\Program Files\\SQLBI\\Bravo\\Bravo.exe",
  "arguments": "--server=\"%server%\" --database=\"%database%\"",
  "iconData": "image/png;base64,...w=="
}
```
Does the `path` contain the correct path to the existing Bravo installation folder on your PC ?

**Comment by Ggithub2020** [comment]
![image](https://user-images.githubusercontent.com/73087775/175834272-422fefe4-6cd6-4b36-a57d-ed8a6c41603c.png)

**Comment by Ggithub2020** [comment]
Thanks, its working now:)

**Comment by Ggithub2020** [comment]
bug fixed:)
