### ISSUE TITLE
Spelling Mistake in Time Intelligence Measures

### ISSUE THREAD

**Issue by tjessome** [sql-bi/Bravo#455]
### Describe the problem

Within the "Growth over full period" time intelligence measures, there is a minor spelling mistake in the autogenerated measure name for "QTDOPQ % <Measure Name>". Currently, the measure is named "Q**DT**OPQ %" (The "T" and "D" are switched).

### Bravo version

0.9.5 (0.9.8190.17886)

### Tabular model

Power BI Desktop, import mode

### Power BI

Version: 2.105.923.0 64-bit (May 2022)

**Comment by albertospelta** [comment]
@tjessome Thanks for reporting! This fix will be available in next release

**Comment by albertospelta** [comment]
Fixed in version [0.9.6](https://github.com/sql-bi/Bravo/releases/tag/v0.9.6)
