### ISSUE TITLE
YTD does reflect Fiscal Year Start

### ISSUE THREAD

**Issue by scsuitguy** [sql-bi/Bravo#458]
### Describe the problem

Selected July as the first month of the fiscal year, but YTD resets in January.

### Bravo version

0.9.5 (0.9.8190.17886)

### Tabular model

Power BI Dataset

### Power BI

Power BI Desktop Version: 2.107.841.0 64-bit (July 2022)

### Screenshots

![ytd_snip](https://user-images.githubusercontent.com/69591050/180700324-a10a9e21-f175-46c7-80a3-d6aa5a9e4b0a.png)
![bravo_config](https://user-images.githubusercontent.com/69591050/180700459-d68e9b1c-1152-4a53-8497-2fa0376bb4b2.png)

**Comment by albertospelta** [comment]
In the current version, all measures created by the standard calendar template are based on the solar calendar date and not on the fiscal date. We are evaluating the possibility of also providing measures based on the fiscal calendar in a future version but at the moment we do not have a timeline for this.

To get the measure based on the fiscal date, you can manually duplicate the YTD measure and add the `YearEndDate` parameter to the `DATESYTD` function, as in the following example. The `YearEndDate` param is an optional string with a date that defines the year-end date.

![isssue-458-TODO](https://user-images.githubusercontent.com/1957788/182129574-b652d97d-e262-42f7-966e-97f94f035889.png)

**Comment by albertospelta** [comment]
Added in version [0.9.6](https://github.com/sql-bi/Bravo/releases/tag/v0.9.6)

This version includes the new fiscal calendar templates.

![image](https://user-images.githubusercontent.com/1957788/189939080-52d57298-1838-40a4-a3ea-efb838c631ee.png)
