### ISSUE TITLE
Expanding the view box for columns not used by the model

### ISSUE THREAD

**Issue by suianypatricia** [sql-bi/Bravo#504]
### The feature request

When I click on "Show unreferenced columns" and "Group by Table", I can see the list of what is not being done. The problem is that I can't change the size of the column view box, being limited to viewing 3 columns at a time.
You can only resize sideways, not down.
<img width="611" alt="Captura de tela 2022-10-20 111552" src="https://user-images.githubusercontent.com/75287691/196973675-eb3d13ef-99b1-40b1-afd4-c4d7f125fff2.png">

### Proposed solution

It would be great to be able to resize down for an optimization in the visualization of these columns, adding this option, it would be less tiring to visualize and document each column when working with a giant model.

### Additional context

In the same way that it is possible to resize the list of columns to the side, such as table, cardinality, size and weight, it would be perfect if you could increase the number of tables to view which is currently fixed at 3.

<img width="644" alt="Captura de tela 2022-10-20 112524" src="https://user-images.githubusercontent.com/75287691/196976059-a7ef491e-9c86-45a7-a721-c67e33a05333.png">

**Comment by albertospelta** [comment]
Hi @pauloandrejesus, thanks for your suggestion.
The limit of the three rows displayed in the table may depend on the screen resolution. What is the resolution of your screen?
You can use the scroll wheel on your mouse to zoom in or out by pressing `Ctrl` and scrolling the wheel up or down.
Does the number of rows displayed change when zooming in/out?

**Comment by suianypatricia** [comment]
Who is pauloandrejesus,? I don't understand! Sorry 😊


> Hi @pauloandrejesus, thanks for your suggestion. The limit of the three rows displayed in the table may depend on the screen resolution. What is the resolution of your screen? You can use the scroll wheel on your mouse to zoom in or out by pressing `Ctrl` and scrolling the wheel up or down. Does the number of rows displayed change when zooming in/out?

**Comment by suianypatricia** [comment]
> Hi @pauloandrejesus, thanks for your suggestion. The limit of the three rows displayed in the table may depend on the screen resolution. What is the resolution of your screen? You can use the scroll wheel on your mouse to zoom in or out by pressing `Ctrl` and scrolling the wheel up or down. Does the number of rows displayed change when zooming in/out?

Hi, albertospelta thanks for the reply. The limit of the three tools displayed in the table really depends on the screen resolution, but the reading required when using other tools, Excel for example, everything stays. The resolution that was in use was set to 150%, the recommended option. I changed it to 100% and it actually shows other lines, but in other tools the reading is bad.

**Comment by albertospelta** [comment]
> Who is pauloandrejesus,? I don't understand! Sorry 😊
> 
> > Hi @pauloandrejesus, thanks for your suggestion. The limit of the three rows displayed in the table may depend on the screen resolution. What is the resolution of your screen? You can use the scroll wheel on your mouse to zoom in or out by pressing `Ctrl` and scrolling the wheel up or down. Does the number of rows displayed change when zooming in/out?

Just fixed my comment, my mistake Sorry :-)

**Comment by albertospelta** [comment]
> Hi, albertospelta thanks for the reply. The limit of the three tools displayed in the table really depends on the screen resolution, but the reading required when using other tools, Excel for example, everything stays. The resolution that was in use was set to 150%, the recommended option. I changed it to 100% and it actually shows other lines, but in other tools the reading is bad.

If you keep the resolution at 150% and zoom out in Bravo (pressing Ctrl and scrolling the mouse wheel) what happens?

**Comment by suianypatricia** [comment]
Perfect! It worked. Thank you so much 💖
