### ISSUE TITLE
The Power BI report takes too long to open

### ISSUE THREAD

**Issue by achkata845** [sql-bi/Bravo#514]
### Describe the problem

Error 200: Power BI Desktop process is opening or the Analysis Services instance is not yet ready.

### Bravo version

1.0.0 (1.0.8339.28087)

### Tabular model

Power BI Desktop, import mode

### Power BI

Version: 2.110.805.0 64-bit (October 2022)

### Screenshots

![image](https://user-images.githubusercontent.com/113461596/199437989-232a4caf-ad1b-4390-8a21-96a06e41efe9.png)
![image](https://user-images.githubusercontent.com/113461596/199438034-c02326fa-c4c8-48ae-8eda-ff892c54059a.png)

**Comment by albertospelta** [comment]
@achkata845 Which option did you use to connect Bravo to the Power BI report?
Did you select an active report from the "Open \ ActiveReports on Power BI Desktop" panel or did you use the "Browse ..." option?

![image](https://user-images.githubusercontent.com/1957788/199449289-95d4e684-a60c-4d47-9efd-f63dab6336fb.png)

**Comment by achkata845** [comment]
Hello Alberto,

I used the browse button. After that the report needed to be opened and this took very long time. When the report was loaded in the active reports after being opened there was no issue loading it.

**Comment by albertospelta** [comment]
The "Browse" button has a timeout of 2 minutes by default and if the report takes longer to load then this error is shown. 
I think we can increase this value. How long does your report take to load?

**Comment by achkata845** [comment]
It took approx 4 min and 30 sec to load.

**Comment by albertospelta** [comment]
I just pushed a change that increases the timeout value to 5 minutes, this fix will be available in the next release.
I am closing this issue, but feel free to reopen in case of further issues/questions. Thanks @achkata845!

**Comment by albertospelta** [comment]
Fixed in version [1.0.1](https://github.com/sql-bi/Bravo/releases/tag/v1.0.1)
