### ISSUE TITLE
Measure formatting Failed - XMLA read/write is not enabled

### ISSUE THREAD

**Issue by JayDoc386** [sql-bi/Bravo#519]
### Describe the problem

Error HTTP/500: Internal Server Error.
Failed to save modifications to the server. Error returned: 'It looks like you can't make changes to this dataset. Please contact a capacity administrator to make sure XMLA read/write support is enabled in the capacity settings on the Power BI Premium capacity, and then try again. For additional information, see 'XMLA read/write support' in the product documentation.

Technical Details:
RootActivityId: b991c3c7-686c-4d5c-a14c-044b49ddac2e
Date (UTC): 11/2/2022 6:23:13 PM
'.

### Bravo version

1.0.0 (1.0.8339.28087)

### Tabular model

Power BI Dataset

### Power BI

Power BI Desktop version October 2022

### Anything else ?

Trace Id: 00-288ecc64df92224f29e95297b6b2c0c1-a8320d7a734a8b3a-00

**Comment by albertospelta** [comment]
Hi @JayDoc386, in order for Bravo to perform the update, the XMLA endpoint property must be enabled for read-write. As long as this setting is not active, Bravo can only read the dataset and not modify(write) it.

You can find here the 'XMLA read/write support' docs
https://learn.microsoft.com/en-us/power-bi/enterprise/service-premium-connect-tools#enable-xmla-read-write

**Comment by albertospelta** [comment]
I just pushed a minor fix to prevent this message from being reported as an application error `Error HTTP/500: Internal Server Error`

**Comment by albertospelta** [comment]
@JayDoc386 I am closing this issue because it is not an error but an informational message that suggests enabling read/write support for the XMLA endpoint. Feel free to reopen in case of further questions. Thanks!

**Comment by albertospelta** [comment]
Added in version [1.0.1](https://github.com/sql-bi/Bravo/releases/tag/v1.0.1)
