### ISSUE TITLE
Trying to save a VPAX file generated an error.

### ISSUE THREAD

**Issue by dgwilson** [sql-bi/Bravo#520]
### Describe the problem

Error HTTP/500: Internal Server Error.
The query referenced calculated column 'CALENDAR_DIM'[Quarter-CY] which does not hold any data because there is an error in its expression.

### Bravo version

1.0.0 (1.0.8339.28087)

### Tabular model

Power BI Desktop, import mode

### Power BI

Power BI Desktop version October 2022

### Steps to reproduce the behavior

1. Click on option to save VPAX file - enter location and save...
2. Crash/error message occurred after "circling" for a short while.

### Anything else ?

Trace Id: 00-d1084d3cfa7fd9376f5c2a78239ed55e-7e7ee1bfe38cab3c-00

**Comment by albertospelta** [comment]
@dgwilson I cannot find this error in telemetry, and unfortunately I am unable to reproduce the error.
Can you check if telemetry in Bravo is enabled and try the same steps again to recreate the error?

**Comment by dgwilson** [comment]
Confirming Telemetry is enabled.
I have reproduced the error (same actions again).

Not my model fortunately. There's a lot of local date tables! I've request that be delt with.
"Your dataset is 640.66MB large and contains 2,336 columns, 2083 of which are not referenced within the model".
I very very much suspect that local date tables are most of these.


Error HTTP/500: Internal Server Error.
The query referenced calculated column 'CALENDAR_DIM'[Quarter-CY] which does not hold any data because there is an error in its expression.
Trace Id: 00-aa621ae1c18232817a84a2616f0c2293-7b8f93a40a536982-00
Version: 1.0.0 (1.0.8339.28087)

{"name":"[HOST] UnhandledException","objects":["Microsoft.AnalysisServices.AdomdClient.AdomdErrorResponseException: The query referenced calculated column 'CALENDAR_DIM'[Quarter-CY] which does not hold any data because there is an error in its expression.\r\n   at Microsoft.AnalysisServices.AdomdClient.XmlaClient.CheckForSoapFault(XmlReader reader, XmlaResult xmlaResult, Boolean throwIfError)\r\n   at Microsoft.AnalysisServices.AdomdClient.XmlaClient.SendMessage(Boolean endReceivalIfException, Boolean readSession, Boolean readNamespaceCompatibility)\r\n   at Microsoft.AnalysisServices.AdomdClient.XmlaClient.ExecuteStatement(String statement, IDictionary connectionProperties, IDictionary commandProperties, IDataParameterCollection parameters, Boolean isMdx)\r\n   at Microsoft.AnalysisServices.AdomdClient.AdomdConnection.XmlaClientProvider.Microsoft.AnalysisServices.AdomdClient.IExecuteProvider.ExecuteTabular(CommandBehavior behavior, ICommandContentProvider contentProvider, AdomdPropertyCollection commandProperties, IDataParameterCollection parameters)\r\n   at Microsoft.AnalysisServices.AdomdClient.AdomdCommand.ExecuteReader(CommandBehavior behavior)\r\n   at Dax.Metadata.Extractor.StatExtractor.LoadRelationshipStatistics(Int32 sampleRows, Boolean analyzeDirectQuery)\r\n   at Dax.Metadata.Extractor.StatExtractor.UpdateStatisticsModel(Model daxModel, IDbConnection connection, Int32 sampleRows, Boolean analyzeDirectQuery)\r\n   at Sqlbi.Bravo.Infrastructure.Helpers.VpaxToolsHelper.GetDaxModel(TabularConnectionWrapper connectionWrapper, CancellationToken cancellationToken, Boolean includeStatistics, Int32 sampleRows) in D:\\a\\1\\s\\src\\Infrastructure\\Helpers\\VpaxToolsHelper.cs:line 57\r\n   at Sqlbi.Bravo.Infrastructure.Helpers.VpaxToolsHelper.ExportVpax(TabularConnectionWrapper connection, String path, CancellationToken cancellationToken) in D:\\a\\1\\s\\src\\Infrastructure\\Helpers\\VpaxToolsHelper.cs:line 13\r\n   at Sqlbi.Bravo.Services.AnalyzeModelService.ExportVpax(PBIDesktopReport report, String path, CancellationToken cancellationToken) in D:\\a\\1\\s\\src\\Services\\AnalyzeModelService.cs:line 112\r\n   at Sqlbi.Bravo.Controllers.AnalyzeModelController.ExportVpax(PBIDesktopReport report, CancellationToken cancellationToken) in D:\\a\\1\\s\\src\\Controllers\\AnalyzeModelController.cs:line 151\r\n   at lambda_method18(Closure , Object , Object[] )\r\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.SyncActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)\r\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeActionMethodAsync()\r\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)\r\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeNextActionFilterAsync()\r\n--- End of stack trace from previous location ---\r\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)\r\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)\r\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()\r\n--- End of stack trace from previous location ---\r\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|25_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)\r\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)\r\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)\r\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeFilterPipelineAsync()\r\n--- End of stack trace from previous location ---\r\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)\r\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)\r\n   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)\r\n   at Microsoft.AspNetCore.Authorization.Policy.AuthorizationMiddlewareResultHandler.HandleAsync(RequestDelegate next, HttpContext context, AuthorizationPolicy policy, PolicyAuthorizationResult authorizeResult)\r\n   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)\r\n   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)\r\n   at Hellang.Middleware.ProblemDetails.ProblemDetailsMiddleware.Invoke(HttpContext context)"],"time":1667502161879}

**Comment by dgosbell** [comment]
So the following would seem to be the critical part of the error message:
```
The query referenced calculated column 'CALENDAR_DIM'[Quarter-CY] 
which does not hold any data because there is an error in its expression
```

Have you tried fixing the error in that calculated column expression or even just temporarily stubbing it out with a constant like `=1`  to see if this fixes the problem?

**Comment by dgwilson** [comment]
As suggested. I "fixed" the erroring columns with hard coded values. 
I have now successfully saved the VPAX file.

**Comment by albertospelta** [comment]
Thank you for the help @dgosbell!
