### ISSUE TITLE
Issue connecting to PBI Government Service (cloud)

### ISSUE THREAD

**Issue by albertospelta** [sql-bi/Bravo#538]
_Originally posted by @vansree in https://github.com/sql-bi/Bravo/discussions/537#discussioncomment-4148901_

I am NOT able to and hence posted the issue.

Steps to reproduce:

1. Launch Bravo for Power BI - v1.0.0
2. Click "Connect to Power BI Service"
3. You will see "Open" window/dialog.
    Red under line on "Datasets on powerbi.com"
    (active tab)

    Message shows
	"You are not connected to Power BI - please sign in to proceed."

	"Sign In" button

4. Click "Sign In" button
5. You will see the dialog "Power BI"

	Enter your email address
![image](https://user-images.githubusercontent.com/49765261/201984021-3487edd7-9bbf-4724-b4ac-b20ba66c58bd.png)
	
	a small message will be shown briefly, "Checking..."

	Finally, you will get "Please enter a valid Power BI account."

...

Please let me know the next steps in resolving

**Comment by awatsky** [comment]
Hey @albertospelta, I am experiencing the same issue that @vansree is experiencing. Here's some more information...
I am getting  [HOST] AppWindow.InitializeWebViewAsync.AdditionalBrowserArguments with the system proxy.

![image](https://user-images.githubusercontent.com/20262286/202003397-c39fe82a-2fb9-4f46-86b0-56f48eafeeaf.png)

I have Authenticate in Browser Enabled.

When I first put my e-mail address in, I do get the option to Sign In. 

![image](https://user-images.githubusercontent.com/20262286/202003755-e5624ec8-407e-4963-b588-3b5850ae2773.png)

Once I attempt to Sign In nothing happens (Browser does not open no request for authentication). The button stays lit. I can click it again. Again, no authentication appears. Now, the button is grayed out (disabled).  I close the window and try again, now I get the message, Please enter a valid Power BI account. 

![image](https://user-images.githubusercontent.com/20262286/202004348-58f72af4-6478-406a-aa4c-49eeb4c8c954.png)

I had Verbose logging enabled. It appears that the app is trying to hit against https://api.powerbi.com and not https://api.powerbigov.us. as once I click Sign In 

{"name":"[HOST] PBICloudSettingsService.GetEnvironmentDiscoveryBaseUri","objects":["https://api.powerbi.com/"],"time":1668541220366} appears.

![image](https://user-images.githubusercontent.com/20262286/202005064-5885bf8a-fe59-4425-8b20-54f87c001f7b.png)

It is however, passing the correct Sign In service endpoint.

![image](https://user-images.githubusercontent.com/20262286/202005539-a34905cb-122a-4070-98e3-e2b7f7c5d4b6.png)

It is returning UnhandledException 401 (Unauthorized).  When I first try to Sign In (When I can click the button)

{_"name":"[HOST] UnhandledException","objects":["System.Net.Http.HttpRequestException: Response status code does not indicate success: 401 (Unauthorized).\r\n   at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()\r\n   at Sqlbi.Bravo.Infrastructure.Services.PowerBI.PBICloudSettingsService.GetTenantClusterAsync(String accessToken, CancellationToken cancellationToken) in D:\\a\\1\\s\\src\\Infrastructure\\Services\\PowerBI\\PBICloudSettingsService.cs:line 53\r\n   at Sqlbi.Bravo.Infrastructure.Services.PowerBI.PBICloudAuthenticationService.SignInAsync(String userPrincipalName, IPBICloudEnvironment environment, CancellationToken cancellationToken) in D:\\a\\1\\s\\src\\Infrastructure\\Services\\PowerBI\\PBICloudAuthenticationService.cs:line 70\r\n   at Sqlbi.Bravo.Services.AuthenticationService.PBICloudSignInAsync(String userPrincipalName, IPBICloudEnvironment environment, CancellationToken cancellationToken) in D:\\a\\1\\s\\src\\Services\\AuthenticationService.cs:line 82\r\n   at Sqlbi.Bravo.Controllers.AuthenticationController.PBICloudSignInAsync(PBICloudAuthenticationRequest request, CancellationToken cancellationToken) in D:\\a\\1\\s\\src\\Controllers\\AuthenticationController.cs:line 61\r\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)\r\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)\r\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)\r\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)\r\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)\r\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)\r\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)\r\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)\r\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)\r\n   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)\r\n   at Microsoft.AspNetCore.Authorization.Policy.AuthorizationMiddlewareResultHandler.HandleAsync(RequestDelegate next, HttpContext context, AuthorizationPolicy policy, PolicyAuthorizationResult authorizeResult)\r\n   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)\r\n   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)\r\n   at Hellang.Middleware.ProblemDetails.ProblemDetailsMiddleware.Invoke(HttpContext context)"],"time":1668539727715}_


Once I get: Please enter a valid Power BI account. The response is not 403 (Forbidden)

{"name":"[HOST] UnhandledException","objects":["System.Net.Http.HttpRequestException: Response status code does not indicate success: 403 (Forbidden).\r\n   at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()\r\n   at Sqlbi.Bravo.Infrastructure.Services.PowerBI.PBICloudSettingsService.GetEnvironmentsAsync(String userPrincipalName, CancellationToken cancellationToken) in D:\\a\\1\\s\\src\\Infrastructure\\Services\\PowerBI\\PBICloudSettingsService.cs:line 79\r\n   at Sqlbi.Bravo.Infrastructure.Services.PowerBI.PBICloudAuthenticationService.GetEnvironmentsAsync(String userPrincipalName, CancellationToken cancellationToken) in D:\\a\\1\\s\\src\\Infrastructure\\Services\\PowerBI\\PBICloudAuthenticationService.cs:line 44\r\n   at Sqlbi.Bravo.Services.AuthenticationService.GetPBICloudEnvironmentsAsync(String userPrincipalName, CancellationToken cancellationToken) in D:\\a\\1\\s\\src\\Services\\AuthenticationService.cs:line 74\r\n   at Sqlbi.Bravo.Controllers.AuthenticationController.GetPBICloudEnvironmentsAsync(String userPrincipalName, CancellationToken cancellationToken) in D:\\a\\1\\s\\src\\Controllers\\AuthenticationController.cs:line 46\r\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)\r\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)\r\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)\r\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)\r\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)\r\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)\r\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)\r\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)\r\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)\r\n   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)\r\n   at Microsoft.AspNetCore.Authorization.Policy.AuthorizationMiddlewareResultHandler.HandleAsync(RequestDelegate next, HttpContext context, AuthorizationPolicy policy, PolicyAuthorizationResult authorizeResult)\r\n   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)\r\n   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)\r\n   at Hellang.Middleware.ProblemDetails.ProblemDetailsMiddleware.Invoke(HttpContext context)"],"time":1668540251930}

I have tried all proxy options and combinations possible. I found that I can get the tutorial videos to load when setting to System. Doesn't matter if I have the custom credentials or not. Either way it loads. All other methods do not appear to work. So at least the proxy is passing correctly. 
![image](https://user-images.githubusercontent.com/20262286/202010385-ecf38965-5efe-43bc-862a-f8905d6355c7.png)

**Comment by albertospelta** [comment]
Hi @vansree, could you please enable the verbose diagnostic in the options panel?

![image](https://user-images.githubusercontent.com/1957788/202008144-028a95c2-d0d1-4acb-a6b0-8d95d2815b2b.png)

Once you have enabled verbose diagnostics and restarted Bravo can you try sign in again?
Are there any error messages in the diagnostic panel? Could you share here the messages you get?

Here is what is displayed for my account - three environments are available.

![image](https://user-images.githubusercontent.com/1957788/202017684-0f37d28e-8a24-404a-a9fe-5c07a20c5acf.png)

**Comment by albertospelta** [comment]
Hi @awatsky, thanks a lot for the detailed information! I am trying to figure out what might be causing these problems but unfortunately I don't have a GCC account so I can't test it. I really appreciate your support in this regard 👍.

Could you please copy and share here the `[HOST] PBICloudSettingsService.GetEnvironmentsAsync` output message? 

![image](https://user-images.githubusercontent.com/1957788/202020930-c60adb1a-ee47-4500-a931-0256e7179264.png)

Could you also share the output of these CMD commands ? (More details here https://github.com/microsoft/Federal-Business-Applications/tree/main/whitepapers/power-bi-registry-settings)

`reg query "HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Microsoft Power BI" /v PowerBIDiscoveryUrl`
`reg query "HKEY_LOCAL_MACHINE\SOFTWARE\WOW6432Node\Policies\Microsoft\Microsoft Power BI" /v PowerBIDiscoveryUrl`

Thanks!

**Comment by vansree** [comment]
> Hi @vansree, could you please enable the verbose diagnostic in the options panel?
> 
> ![image](https://user-images.githubusercontent.com/1957788/202008144-028a95c2-d0d1-4acb-a6b0-8d95d2815b2b.png)
> 
> Once you have enabled verbose diagnostics and restarted Bravo can you try sign in again? Are there any error messages in the diagnostic panel? Could you share here the messages you get?
> 
> Here is what is displayed for my account - three environments are available.
> 
> ![image](https://user-images.githubusercontent.com/1957788/202017684-0f37d28e-8a24-404a-a9fe-5c07a20c5acf.png)

{"name":"[HOST] PBICloudSettingsService.GetEnvironmentDiscoveryBaseUri","objects":["https://api.powerbi.com/"],"time":1668550453671}

![image](https://user-images.githubusercontent.com/49765261/202036591-3362ad5c-e871-4b4a-af0f-d3b9f7e0c172.png)

![image](https://user-images.githubusercontent.com/49765261/202036675-22270faf-3df8-4830-b9fe-6c4800cd2611.png)



{"name":"[HOST] PBICloudSettingsService.GetEnvironmentsAsync","objects":[{"environments":[{"cloudName":"USGovCloud","azureActiveDirectoryUri":"https://login.microsoftonline.com","azureResourceManagerUri":"https://management.usgovcloudapi.net","azureResourceManagerAadResource":"https://management.core.usgovcloudapi.net","azureServiceManagementUri":"https://management.core.usgovcloudapi.net","microsoftGraphUri":"https://graph.microsoft.com","powerBiUri":"https://api.powerbigov.us","powerBiAadResource":"https://analysis.usgovcloudapi.net/powerbi/api","azureStorageUriSuffix":"core.usgovcloudapi.net","azureStorageAadResource":"https://storage.azure.com/","services":[{"name":"aad","endpoint":"https://login.microsoftonline.com/common","resourceId":"","allowedDomains":null},{"name":"aad-organizations","endpoint":"https://login.microsoftonline.com/organizations","resourceId":"","allowedDomains":null},{"name":"arm","endpoint":"https://management.usgovcloudapi.net","resourceId":"https://management.core.usgovcloudapi.net","allowedDomains":null},{"name":"azure-service-management","endpoint":"https://management.core.usgovcloudapi.net","resourceId":"","allowedDomains":null},{"name":"azure-auth","endpoint":"https://login.microsoftonline.com","resourceId":"","allowedDomains":null},{"name":"azure-storage","endpoint":"core.usgovcloudapi.net","resourceId":"https://storage.azure.com/","allowedDomains":null},{"name":"msgraph","endpoint":"https://graph.microsoft.com","resourceId":"","allowedDomains":null},{"name":"powerbi-marketing","endpoint":"https://powerbigov.us","resourceId":"","allowedDomains":null},{"name":"powerbi-frontend","endpoint":"https://app.powerbigov.us","resourceId":"","allowedDomains":null},{"name":"custom-visual-endpoint","endpoint":"https://pbivisuals.powerbigov.us","resourceId":"","allowedDomains":null},{"name":"powerbi-backend","endpoint":"https://api.powerbigov.us","resourceId":"https://analysis.usgovcloudapi.net/powerbi/api","allowedDomains":["*.analysis.usgovcloudapi.net"]},{"name":"bingmaps-control","endpoint":"https://www.bing.com/api/maps/mapcontrol","resourceId":"","allowedDomains":null},{"name":"bingmaps-geocoding","endpoint":"https://dev.virtualearth.net/REST/v1/Locations","resourceId":"","allowedDomains":null},{"name":"bingmaps-spatialdata","endpoint":"https://platform.bing.com/geo/spatial/v1/public/Geodata","resourceId":"","allowedDomains":null},{"name":"rdl-anaheim","endpoint":"https://paginated-reports.powerbigov.us","resourceId":"","allowedDomains":null},{"name":"mip-rms","endpoint":"https://api.aadrm.com","resourceId":"","allowedDomains":null},{"name":"mip-scc","endpoint":"https://dataservice.protection.outlook.com","resourceId":"https://syncservice.o365syncservice.com/","allowedDomains":null}],"clients":[{"name":"powerbi-desktop","appId":"6807062e-abc9-480a-ae93-9f7deee6b470","redirectUri":"urn:ietf:wg:oauth:2.0:oob","appInsightsId":"81472945-6c45-fb2c-beee-0cb49c0eff75","localyticsId":"945568c539b1ec6fc69fc1e-f2eaded0-5da6-11e6-b2b0-00342b7f5075","appInsightsConnectionString":"InstrumentationKey=81472945-6c45-fb2c-beee-0cb49c0eff75;EndpointSuffix=applicationinsights.us"},{"name":"powerbi-mobile","appId":"ce76e270-35f5-4bea-94ff-eab975103dc6","redirectUri":"https://*.analsysis.usgovcloudapi.net/","appInsightsId":"e0b5474d-fc7e-45ee-b360-adcf14f0446a","localyticsId":"de09704f7f15e9cb4b96e86-129b8d36-5da7-11e6-720c-002dea3c3994","appInsightsConnectionString":""},{"name":"powerbi-gateway","appId":"85497d63-b21f-44e6-b91a-5e337b063302","redirectUri":"urn:ietf:wg:oauth:2.0:oob","appInsightsId":"75ef3aac-72ec-f957-8f46-7368ef638d9c","localyticsId":"1c45f440702d0700fb71e1a-d7c1929c-5da6-11e6-720c-002dea3c3994","appInsightsConnectionString":"InstrumentationKey=75ef3aac-72ec-f957-8f46-7368ef638d9c;EndpointSuffix=applicationinsights.us"},{"name":"powerbi-excel-addin","appId":"76adac1f-971e-49e1-92eb-db72f5df6b46","redirectUri":"urn:ietf:wg:oauth:2.0:oob","appInsightsId":"ac6535e0-835b-fd8e-89d7-006e1488cbeb","localyticsId":"6e665f82b6bb29b73c43d6f-62f23c66-5da7-11e6-862e-0086bc74ca0f","appInsightsConnectionString":"InstrumentationKey=ac6535e0-835b-fd8e-89d7-006e1488cbeb;EndpointSuffix=applicationinsights.us"},{"name":"powerbi-msolap","appId":"7b12a2ce-4704-4349-9388-d80a8e23116d","redirectUri":"urn:ietf:wg:oauth:2.0:oob","appInsightsId":"90eeb8ac-1dcb-f1ae-a5bb-2f4700a9d85e","localyticsId":"8d0e4826cc735f6d0fdb329-bce8f6a4-5da6-11e6-b2b0-00342b7f5075","appInsightsConnectionString":"InstrumentationKey=90eeb8ac-1dcb-f1ae-a5bb-2f4700a9d85e;EndpointSuffix=applicationinsights.us"},{"name":"powerbi-report-builder","appId":"f0b72488-7082-488a-a7e8-eada97bd842d","redirectUri":"https://login.microsoftonline.com/common/oauth2/nativeclient","appInsightsId":"b555e803-c99d-f5ef-8464-fdd264c4eecd","localyticsId":"69a3b47b7ad942068376385-bdbf4cc8-a808-410e-9da6-9bb8f76e8a09","appInsightsConnectionString":"InstrumentationKey=b555e803-c99d-f5ef-8464-fdd264c4eecd;EndpointSuffix=applicationinsights.us"}],"clientConfigs":{"mipCloudIdentifier":6}}]}],"time":1668550455388}

**Comment by albertospelta** [comment]
@awatsky That's great news indeed!

> I also wanted to let you know it appears that the previous versions did not fix this issue either. It seems like this has been an issue for all other versions except the Dev version we originally worked on.

You are definitely right, this problem existed in all previous versions as well

@vansree please let us know if it worked for you too. Thanks!

**Comment by albertospelta** [comment]
>I am willing to help with testing from a sovereign cloud perspective (using GCC).

Sure, many thanks @awatsky! This is great news 👍

**Comment by vansree** [comment]
Hi,

I downloaded the dev version and able to connect. The issue seems to be resolved. I wonder what fix you did, more for technical knowledge. Appreciated the replies and fix.
 
I will update if I found any errors. Keep the issue open for the next few days and close it if I don't post any. 

Regards
Sree

**Comment by albertospelta** [comment]
> I wonder what fix you did, more for technical knowledge.

@vansree, the bug was in the `GetTenantCluster` API which always hit against the PBI commercial endpoint https://api.powerbi.com/ instead of using the GCC endpoint https://api.powerbigov.us/

This is the commit that fixed the bug https://github.com/sql-bi/Bravo/pull/539/commits/04239f35b1a5555158afb99c769885a5095a0c64#diff-98ee11d7bb37796548984cee4b46c07ddc5d9f7d7b5d97351c20cffde6da0494

**Comment by albertospelta** [comment]
Fixed in version [1.0.1](https://github.com/sql-bi/Bravo/releases/tag/v1.0.1)

**Comment by vansree** [comment]
@albertospelta 

I downloaded the 1.0.1 version and am able to connect to Power BI. Thank you for working on it and fixing it.

**Thought to think:** pls. consider for future, may be a different tab names like "Datasets on Power BI Gov - US". Currently it is showing as "Datasets on PowerBi.com"

![image](https://user-images.githubusercontent.com/49765261/207197516-1643682e-fa58-426f-a367-6984ee268dd0.png)
