### ISSUE TITLE
In Time Intelligence, Preview Changes, Every folder shows "M" as modified regardless of changes.

### ISSUE THREAD

**Issue by mscottsewell** [sql-bi/Bravo#541]
### Describe the problem

When I preview the changes for Time Intelligence, it shows every folder as having Modified measures - even when there are no changes to be made -
Even when there are deletes or new measures in sub-folders there's no visibility at the higher level to indicate that I should open each folder to review. 
I can expand to just a list of measures, but it still shows as if every measure would be changed.

### Bravo version

1.0.0 (1.0.8339.28087)

### Tabular model

Power BI Desktop, import mode

### Power BI

Version: 2.110.1085.0 64-bit (October 2022)

### Steps to reproduce the behavior

1. Have a report with at least some measures in display folders 
2. Use Bravo to generate the Time Intelligence folder for most but not all Target Measures
3. Preview and apply changes
4. Click 'Done' and then immediately click Preview Changes again - All measures show as needing modification
5. Go back to Time intelligence tab, and Add a Measure and Unselect a measure in the Target Measures
6. Preview Changes - The changes will be in the list, but they aren't readily visible since *everything* at the highest level already shows as 'M' to be modified, and you can't find 'real' changes without clicking and opening every folder.

**Comment by albertospelta** [comment]
Hi @mscottsewell, thanks for reporting this! I just realized that the same problem also exists in the preview of the data tables where 'M' is shown even if no modification has been done

![image](https://user-images.githubusercontent.com/1957788/202897689-2955b5cf-c760-4ad6-8d77-d8f90f20697a.png)

**Comment by albertospelta** [comment]
@mscottsewell I just pushed a fix for this issue, if you want to test you can try the latest internal build by changing the update channel from `Stable` to `Dev` in the Bravo options panel and then following the download link. Thanks!

**Comment by mscottsewell** [comment]
Thank you! I will test it later today.
