### ISSUE TITLE
Christmas Day In Lieu 2022

### ISSUE THREAD

**Issue by yatesey5791** [sql-bi/Bravo#555]
### Describe the problem

The holidays table is showing the 28th December as a day in lieu of Christmas Day in the UK which it is not, this is causing the working days in December to be 19 not 20. 

### Bravo version

v1.0.0 (1.0.8339.28087)

### Tabular model

Power BI Desktop, import mode

### Power BI

power bi desktop 2.111.590.0 64-bit (November 2022)

### Steps to reproduce the behavior

not required, need to understand why that date has been marked as a holiday as it should be 27th

### Screenshots

![bravo, issue](https://user-images.githubusercontent.com/101274964/205944144-a964de17-4bec-4467-bead-5fb3edf85b48.png)

**Comment by yatesey5791** [comment]
its ok, figured it out by editing the code in the definitions file

**Comment by ChristianBellLVS** [comment]
> its ok, figured it out by editing the code in the definitions file

Do you mind sharing your solution? I am having the same issue (but Canadian!)

**Comment by albertospelta** [comment]
We have identified the issue, and the fix is available in version [1.0.8](https://github.com/sql-bi/Bravo/releases/tag/v1.0.8)
