### ISSUE TITLE
Manage Dates - Item '%' already exists in the collection

### ISSUE THREAD

**Issue by sageata** [sql-bi/Bravo#569]
### Describe the problem

Error HTTP/500: Internal Server Error.
Item 'YOY % Longer than higher Bound' already exists in the collection.

### Bravo version

1.0.1 (1.0.8381.30060)

### Tabular model

Power BI Desktop, import mode

### Power BI

Version: 2.112.603.0 64-bit (December 2022)

### Steps to reproduce the behavior

1. Attach to Power BI File
2. Click "Manage Dates"

I attempted to disconnect and reconnect, close and open Bravo, but same result. 

### Screenshots

![SCR-20230109-jak](https://user-images.githubusercontent.com/26434396/211281725-52a4e47c-81ab-45d2-91e9-b6dbbb051080.png)

### Anything else ?

Trace Id: 00-51fc4862c917b29eb178231a4298c710-4a77b6fbd38eace0-00

**Comment by albertospelta** [comment]
Hi @sageata, thanks for reporting the error! This is a known bug in DaxTemplate library (https://github.com/sql-bi/DaxTemplate/issues/9)

I located the bug and a fix will be available shortly.

**Comment by albertospelta** [comment]
@sageata, we pushed a fix for this issue which is available as a development/internal release.

It would be helpful if you could test this version and let us know if the error still occurs. You can get the latest internal build by changing the update channel from `Stable` to `Dev` in the Bravo options panel and then follow the download link. 

Thanks!

**Comment by sageata** [comment]
Thank you, @albertospelta!
I have downloaded the latest dev version and I can confirm that it's fixed.

**Comment by albertospelta** [comment]
Fixed in version [1.0.2](https://github.com/sql-bi/Bravo/releases/tag/v1.0.2)
