### ISSUE TITLE
Leading commas in DAX formatter. 

### ISSUE THREAD

**Issue by WolfX2** [sql-bi/Bravo#612]
### The feature request

When testing out conditions in a calculate statement, sometimes you just wish to "turn off" a condition. 

Add an option in the dax formatter for leading instead of trailing commas. This is advantageous because now you can easily comment out any of the conditions without having to move commas around. 

for example:
```
CALCULATE( 
  [MEASURE], 
  CONDITION1, 
  CONDITION2
)
```

Could be:
```
CALCULATE( 
  [MEASURE]
  , CONDITION1
  --, CONDITION2
)
```

### Proposed solution

Add an option in the dax formatter for leading instead of trailing commas.

This is advantageous because now you can easily comment out any of the conditions without having to move commas around. 

for example:
```
CALCULATE( 
  [MEASURE], 
  CONDITION1, 
  CONDITION2
)
```

Could be:
```
CALCULATE( 
  [MEASURE]
  , CONDITION1
  --, CONDITION2
)
```

**Comment by albertospelta** [comment]
Hi @WolfX2 and thanks for the suggestion. This option is already available in [DaxStudio](https://www.youtube.com/watch?v=YkCMgyTlvXA&t=264s) and [TabularEditor3](https://github.com/TabularEditor/TabularEditor3/discussions/399#discussioncomment-2124335). The goal for Bravo is to keep it simple and easy to use, you should evaluate to use one of these tools for more advanced tasks like writing/testing DAX.
