### ISSUE TITLE
User does not have permission to call the Discover method

### ISSUE THREAD

**Issue by albertospelta** [sql-bi/Bravo#633]
Bom dia, estou com o mesmo problema que o colega acima. Mesmo baixando a nova versão do bravo o Erro HTTP/500 persiste.
Já foi corrigido este bug?
![erro](https://user-images.githubusercontent.com/53009561/230390107-6af8f1a8-65d9-4906-a0a0-3312b925a581.PNG)

_Originally posted by @FontanaMario in https://github.com/sql-bi/Bravo/issues/565#issuecomment-1499050963_

**Comment by albertospelta** [comment]
Hi @FontanaMario, I've created this new issue because the `HTTP/500` is a generic error code that can refer to different types of errors and the issue you are reporting is `User does 'xx@yy' not have permission to call the Discover method` and it's a different error from the one discussed in https://github.com/sql-bi/Bravo/issues/565 which is `Failed to fetch`.

You're getting this error probably because your account is not authorized to access the workspace. 

- Is the dataset you are connecting to in your personal workspace (MyWorkspace)? Or is it in another workspace you created?
- What licensing mode are you using for the workspace (pro/premium per user/..)?  
![image](https://user-images.githubusercontent.com/1957788/230437245-e434cdaf-4c84-4977-adaa-22b7c8fa2012.png)

**Comment by FontanaMario** [comment]
Olá, o conjunto de dados está em um Workspace que eu sou o administrador. Minha Licença é a Pró

**Comment by FontanaMario** [comment]
O conjunto de dados ao qual você está se conectando está em seu espaço de trabalho pessoal (MyWorkspace)? Ou está em outro espaço de trabalho que você criou?
**Resp:** Eu criei e sou o administrador.

Qual modo de licenciamento você está usando para o espaço de trabalho (pro/premium por usuário/..)?
**Resp:** Licença Pró

**Comment by albertospelta** [comment]
Are you using a PowerBI 60-day trial license?

**Comment by FontanaMario** [comment]
Minha licença é paga, já tenho ela a mais de 3 anos.

**Comment by albertospelta** [comment]
It would be helpful if you could share some information from your dataset (those highlighted in green in the box below).
You can access this information by clicking the "Connect to Power BI service" option after enabling detailed diagnostics in the Bravo options panel.

![image](https://user-images.githubusercontent.com/1957788/230445021-db1aeba9-c35e-46fc-8f7f-83984d427a90.png)

**Comment by FontanaMario** [comment]
Bom dia, veja os detalhes do erro:

![image](https://user-images.githubusercontent.com/53009561/230886042-6722970a-5d29-4441-b93e-c2147e1cf2d4.png)
 
![image](https://user-images.githubusercontent.com/53009561/230886113-d7b7e88e-48d5-4aae-a8dd-83cde0fb9f59.png)
![image](https://user-images.githubusercontent.com/53009561/230886216-cfa327f3-9466-4e51-9ad6-8a4e6d6537fc.png)

**Comment by FontanaMario** [comment]
Erro HTTP/500: Internal Server Error.
O usuário '<euii>mario@csprojetos.com</euii>' não tem permissão para chamar o método Descoberta.

Technical Details:
RootActivityId: b3674707-0ad6-498b-b96c-be9c34743c9b
Date (UTC): 4/10/2023 10:22:57 AM

Id de Rastreio: 00-a4a175b23780e87cc243edea691ae5eb-f258c109ddb4a07b-00
Versão: 1.0.2-internal-20230405.1-main-5d530b5b5166cb3d453ad3c77adf671420fc6886 (1.0.8495.28703)

**Comment by albertospelta** [comment]
@FontanaMario is your PowerBI dataset live-connected to an external Analysis Services model like Azure Analysis Service or an on-prem SSAS instance ? In this case, your account requires admin rights on the AAS/SSAS model to be able to connect

**Comment by FontanaMario** [comment]
Boa tarde, veja esta outra conexão que também está ncom erro:

Erro HTTP/500: Internal Server Error.
O usuário '<euii>mario@csprojetos.com</euii>' não tem permissão para chamar o método Descoberta.

Technical Details:
RootActivityId: 88e27643-444e-4b92-a71d-7bf45ea65021
Date (UTC): 4/10/2023 7:33:48 PM

Id de Rastreio: 00-0e07c53ed9d42ab4b0549aea88175cd8-46121c99eb21ce09-00
Versão: 1.0.2-internal-20230405.1-main-5d530b5b5166cb3d453ad3c77adf671420fc6886 (1.0.8495.28703)


![image](https://user-images.githubusercontent.com/53009561/230982463-2b6cde60-4f3b-4559-b8cd-bf69a621cb3b.png)

**Comment by albertospelta** [comment]
@FontanaMario Seems to be the same error. Are these datasets configured to use a live connection to an external datasource?
In the following images you can see an example of two datasets where the first is configured to use a live connection to Azure AS as external data source while the second is configured in [Import mode](https://learn.microsoft.com/en-us/power-bi/connect-data/service-dataset-modes-understand#import-mode).
Would you mind letting me know what kind of data source these datasets are using? 

![image](https://user-images.githubusercontent.com/1957788/231081168-fb068686-dc58-4d3d-beda-034159f56a24.png)

![image](https://user-images.githubusercontent.com/1957788/231080931-33456e44-4bd9-4f80-b07b-1001950f2ce2.png)

**Comment by FontanaMario** [comment]
Bom dia, estou usando o modo importação.

![image](https://user-images.githubusercontent.com/53009561/231139394-f2f17f32-0c08-41cf-9228-96ffd7fefdba.png)

**Comment by FontanaMario** [comment]
Em todas as conexões utilizamos somente o modo importação.

**Comment by albertospelta** [comment]
Hi @FontanaMario! Thanks for the feedback and helpful information you provided. We have identified the issue and pushed a fix which is available as a development/internal release. It would be helpful if you could test this version and let us know if the error still occurs. Thanks!

You can get the latest internal build by changing the update channel from `Stable` to `Dev` in the Bravo options panel and then follow the download link.

**Comment by FontanaMario** [comment]
Bom dia, onde posso baixar esta nova versão par poder testar?

**Comment by FontanaMario** [comment]
Bom dia, esta é a versão mencionada na mensagem acima?

![image](https://user-images.githubusercontent.com/53009561/232458097-98e729e9-6669-4402-ab29-7593be219748.png)

**Comment by FontanaMario** [comment]
Bom dia, baixei a nova versão e testei a conexão. Agora deu certo. Obrigado.

**Comment by albertospelta** [comment]
Fixed in version [1.0.3](https://github.com/sql-bi/Bravo/releases/tag/v1.0.3)

**Comment by FontanaMario** [comment]
Boa tarde,
Tudo bem.

Estou tendo problema para instalar a nova versão do bravo, está dando a seguinte mensagem de erro:

[cid:6844c40c-1f35-4115-957d-b7eedeafb518]




   Atenciosamente,

[cid:9f9f36a3-8353-44b0-88e3-dd8579707032]

________________________________
De: Alberto Spelta ***@***.***>
Enviado: segunda-feira, 17 de abril de 2023 08:04
Para: sql-bi/Bravo ***@***.***>
Cc: Mário B. Fontana ***@***.***>; Mention ***@***.***>
Assunto: Re: [sql-bi/Bravo] User does not have permission to call the Discover method (Issue #633)


Closed #633<https://github.com/sql-bi/Bravo/issues/633> as completed.

**Comment by albertospelta** [comment]
Hi @FontanaMario, unfortunately I can not find detail of the error in your comment, this is probably because pictures and attachments are not included when replying by mail. Would you mind sharing here the error details using the GitHub website and not via email?

**Comment by FontanaMario** [comment]
Bom dia, ao tentar instalar a nova versão está aparecendo um erro veja.

![image](https://github.com/sql-bi/Bravo/assets/53009561/3ce2f300-4b71-4b32-9568-2e5692b8d534)
![image](https://github.com/sql-bi/Bravo/assets/53009561/b7a6e2c2-df31-499e-9a6f-467a9d3a074b)
