### ISSUE TITLE
User does not have permission to call the Discover method

### ISSUE THREAD

**Issue by CezaryIwanicki** [sql-bi/Bravo#655]
### Describe the problem

It is not possible for me to import data from Power Bi Service.
I'm getting an error:

Error HTTP/500: Internal Server Error.
Użytkownik „<euii>Cezary.Iwanicki@convertertec.com</euii>” nie ma uprawnień do wywoływania metody Discover.

Technical Details:
RootActivityId: 2a6afeb1-022c-4003-ab92-6560fd364dba
Date (UTC): 5/9/2023 9:32:08 AM

### Bravo version

1.0.2 (1.0.8480.21768)

### Tabular model

Power BI Dataset

### Power BI

SSAS 2019

### Steps to reproduce the behavior

1. Connect to Power BI Service.
2. Open required Dataset.
3. Got Error message.

### Anything else ?

Trace Id: 00-878c362a588ec4fee1edc246fb6dd0c6-9f0061ed0ba47ad7-00

**Comment by albertospelta** [comment]
Hi @CezaryIwanicki this issue has already been reported in https://github.com/sql-bi/Bravo/issues/633 and the fix will be available in next release.

In the meantime you can use the latest internal `Dev` build (see https://github.com/sql-bi/Bravo/issues/633#issuecomment-1505200567) which already includes this fix.

I'll close this issue as it's a duplicate, but feel free to reopen it if the problem persists. Thanks!

**Comment by CezaryIwanicki** [comment]
Hi,

Thanks for help. 
I'm stunned regarding your response time. Pro 🥇

**Comment by albertospelta** [comment]
Fixed in version [1.0.3](https://github.com/sql-bi/Bravo/releases/tag/v1.0.3)
