### ISSUE TITLE
Fix blurry icon

### ISSUE THREAD

**Issue by danieleperilli** [sql-bi/Bravo#66]
The icon in the application is blurry compared to the icon of the application file.

<img width="692" alt="Notification_Center" src="https://user-images.githubusercontent.com/9072177/151844028-74e8f6c7-9f51-4ec2-b8be-c3b32710f911.png">
.

**Comment by albertospelta** [comment]
Fixed in version [0.9.5](https://github.com/sql-bi/Bravo/releases/tag/v0.9.5)
