### ISSUE TITLE
Bravo saying Not Available

### ISSUE THREAD

**Issue by albertospelta** [sql-bi/Bravo#671]
### Discussed in https://github.com/sql-bi/Bravo/discussions/669

<div type='discussions-op-text'>

<sup>Originally posted by **LesegoT** May 31, 2023</sup>
Hello! Since updating my Power BI Desktop to version 2.117.984.0 (May 2023) my Bravo is showing Not Available in the top right corner. It starts up okay and analyses the model, but I am unable to format DAX or Manage Dates. Nothing else has changed in my environment (same network settings, using System proxy setting). I have uninstalled and re-installed and tried it with different pbix file with no luck, even with files I previously used Bravo to create the Dates table in. What could be the problem?

![Screenshot 2023-05-31 085208](https://github.com/sql-bi/Bravo/assets/30831601/86c2556b-b030-46b9-bd24-c3d46f8643e4)
</div>

**Comment by albertospelta** [comment]
Hi @LesegoT, this issue appears to be similar to [#510](https://github.com/sql-bi/Bravo/issues/510#issuecomment-1296171970) and [#476](https://github.com/sql-bi/Bravo/issues/476#issuecomment-1236872603) and is likely due to a different text format that Power BI Desktop applies to the report name/title depending on the display culture used on your PC. Bravo uses this title to get the report name and this small format difference is the cause of the "NOT AVAILABLE" message.

What is the language used in PBI Desktop and your operating system?
Could you share a screenshot of the PBIX file name and PBIDesktop window title?

![image](https://github.com/sql-bi/Bravo/assets/1957788/7ef82342-cb16-4c5a-8ca0-24b5702254d3)

**Comment by LesegoT** [comment]
Hi @albertospelta, these are my preview settings:
![Screenshot 2023-06-01 091916](https://github.com/sql-bi/Bravo/assets/30831601/fc2201e9-cc4e-46fe-bdf7-fd25133c86fe)

**Comment by albertospelta** [comment]
@LesegoT thank you for the information provided! I have just pushed a fix and a new internal build should be available within 30 minutes, please let me know if this version fixes the issue.

This is a bug in Bravo that does not correctly identify the active report and reports it as "Not Available" when the window title does not contain the suffix ` - Power BI Desktop` - this happens only when the "Save to OneDrive/SharePoint" function is enabled.

![image](https://github.com/sql-bi/Bravo/assets/1957788/8d40c751-5c25-43a9-b195-ce1f27c70c80)

The title of the PBID window has the suffix ` - Power BI Desktop` when the "Save to OneDrive/SharePoint" feature is disabled
![image](https://github.com/sql-bi/Bravo/assets/1957788/0691e3d6-b35c-439e-8bff-f1d8d2feb3f0)

After enabling the feature, the title no longer contains the suffix ` - Power BI Desktop`
![image](https://github.com/sql-bi/Bravo/assets/1957788/2e4441a5-0b65-4477-a6a6-5deb13cf919b)

**Comment by LesegoT** [comment]
Thank you so much @albertospelta! The new build has resolved my issue.

**Comment by albertospelta** [comment]
Fixed in version [1.0.3](https://github.com/sql-bi/Bravo/releases/tag/v1.0.3)
