### ISSUE TITLE
Error 200: Power BI Desktop process is opening or the Analysis Services instance is not yet ready

### ISSUE THREAD

**Issue by CarlosAzabacheEC** [sql-bi/Bravo#680]
### Describe the problem

Error 200: Power BI Desktop process is opening or the Analysis Services instance is not yet ready.

### Bravo version

1.0.2 (1.0.8480.21768)

### Tabular model

Power BI Desktop, import mode

### Power BI

Power BI Desktop

### Screenshots

![image](https://github.com/sql-bi/Bravo/assets/102402527/83777801-12d5-481d-b328-4f1941046937)

**Comment by CarlosAzabacheEC** [comment]
> Hi @CarlosAzabacheEC, an internal build is available which should resolve this error, it would be great if you could test it and let us know if it solves the issue.
> 
> To get the latest internal build you can change the update channel from `Stable` to `Dev` in the options panel as shown in the image. ![image](https://user-images.githubusercontent.com/1957788/245713540-44362b7c-0a55-4bc7-8c5b-7541fc4747eb.png)

Excellent, thanks Alberto. I can now read my boards

**Comment by albertospelta** [comment]
Fixed in version [1.0.3](https://github.com/sql-bi/Bravo/releases/tag/v1.0.3)

**Comment by albertospelta** [comment]
I'm closing this issue as this bug was fixed in version [1.0.3](https://github.com/sql-bi/Bravo/releases/tag/v1.0.3), but feel free to reopen if the problem persists. Thank you!
