### ISSUE TITLE
Manage Dates > Interval | Inactive Relationships does not include Active Relationships

### ISSUE THREAD

**Issue by tabertantrum** [sql-bi/Bravo#686]
### Describe the problem

When selecting Inactive Relationships in Automatic Scan for Date Interval, the expression generated only includes Inactive Relationship columns.

[Bravo Documentation](https://docs.sqlbi.com/bravo/features/manage-dates/) indicates Inactive Relationships should include both Active and Inactive Relationships:

> Active Relationships only considers the date columns that are part of an active relationship.
> Inactive Relationships only considers the date columns that are part of both active and inactive relationships.

### Bravo version

1.0.8566.15194

### Tabular model

Power BI Desktop, import mode

### Power BI

Power BI Desktop version June 2023

### Steps to reproduce the behavior

1. Create a model with both Active and Inactive relationships to Date table
2. Apply Bravo date template with "Inactive Relationships" option chosen
3. Preview changes
4. Review Expression for DateAutoTemplate and confirm that only columns with an Inactive Relationship to Date table are included in the `VAR __FirstYear` and `VAR __LastYear` definitions

**Comment by albertospelta** [comment]
Hi @tabertantrum, thank you for reporting this issue! It's a bug and I have just pushed the fix. 

This fix will be available in next release but, if you are interested in testing the preview build, you can get it by changing the update channel from `Stable` to `Dev` in the Bravo options panel and then follow the download link.

**Comment by tabertantrum** [comment]
Thanks @albertospelta! I have downloaded the Dev version and confirmed all inactive and active relationship fields are properly included when selecting Inactive Relationships.

**Comment by albertospelta** [comment]
Fixed in version [1.0.4](https://github.com/sql-bi/Bravo/releases/tag/v1.0.4)
