### ISSUE TITLE
Error: The specified column was not found in the context at line 3, column 5

### ISSUE THREAD

**Issue by FrankVanZuilen** [sql-bi/Bravo#690]
### Describe the problem

Error HTTP/500: Internal Server Error.
De opgegeven kolom is niet gevonden in de context op regel 3, kolom 5.

### Bravo version

1.0.3 (1.0.8566.15194)

### Tabular model

Power BI Desktop, import mode

### Power BI

June 2023

### Steps to reproduce the behavior

Starting Bravo via External Tools in Power BI desktop already raises errors

### Anything else ?

Trace Id: 00-145758a5495d394c5628652b061981d4-37db6b295b72c450-00

**Comment by albertospelta** [comment]
Hi @FrankVanZuilen, this is a bug that was recently fixed. Could you try the latest internal build and let us know if the problem is solved? You can get it by changing the update channel from `Stable` to `Dev` in the Bravo options panel and then follow the download link.

**Comment by FrankVanZuilen** [comment]
Hi Alberto, That fixed the issue. Thank you and have a good weekend. Frank Van: Alberto Spelta ***@***.***>Datum: vrijdag, 23 juni 2023 om 15:13Aan: sql-bi/Bravo ***@***.***>CC: FrankVanZuilen ***@***.***>, Mention ***@***.***>Onderwerp: Re: [sql-bi/Bravo] New Bravo 1.0.3 version raises errors? (Issue #690)Hi @FrankVanZuilen, this is a bug that was recently fixed. Could you try the latest internal build and let us know if the problem is solved? You can get it by changing the update channel from Stable to Dev in the Bravo options panel and then follow the download link.—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you were mentioned.Message ID: ***@***.***>[ { ***@***.***": "http://schema.org", ***@***.***": "EmailMessage", "potentialAction": { ***@***.***": "ViewAction", "target": "https://github.com/sql-bi/Bravo/issues/690#issuecomment-1604267827", "url": "https://github.com/sql-bi/Bravo/issues/690#issuecomment-1604267827", "name": "View Issue" }, "description": "View this Issue on GitHub", "publisher": { ***@***.***": "Organization", "name": "GitHub", "url": "https://github.com" } } ]

**Comment by albertospelta** [comment]
Fixed in version [1.0.4](https://github.com/sql-bi/Bravo/releases/tag/v1.0.4)
