### ISSUE TITLE
Issue to connect with Power BI with Dynamic Formating String

### ISSUE THREAD

**Issue by bkGulshan** [sql-bi/Bravo#698]
### Describe the problem

Error HTTP/500: Internal Server Error.
The database compatibility level of 1601 is below the minimal compatability level of 2147483647 needed for [model 'Model'].[table 'My Measures'].[measure 'Temperature Inside (Min)' in table 'My Measures'].FormatStringDefinition at PowerBI mode.

### Bravo version

0.9.4 (0.9.8158.22794)

### Tabular model

Power BI Desktop, import mode

### Power BI

Power BI Desktop version July 2023

### Anything else ?

Trace Id: 00-7131cc43531f1b5a98a00ee02b5a2212-7c5d954633470caa-00

**Comment by albertospelta** [comment]
Hi @bkGulshan, dynamic format strings were introduced in PowerBI in May 2023, and Bravo version 0.9.4 does not support this feature. You can resolve this error by updating Bravo to the latest version https://github.com/sql-bi/Bravo/releases/latest
