### ISSUE TITLE
Holiday Name incorrectly translated [da]

### ISSUE THREAD

**Issue by jkoinnovatedk** [sql-bi/Bravo#707]
### Describe the problem

Not exactly a bug, but the column Holiday Name is incorrectly translated to "Ferienavn" in the Date Calendar if you choose 

It should be "Helligdag"

### Bravo version

1.0.5 (1.0.8623.25801)

### Tabular model

Power BI Desktop, import mode

### Power BI

Power BI Desktop

**Comment by albertospelta** [comment]
Fixed in version [1.0.6](https://github.com/sql-bi/Bravo/releases/tag/v1.0.6)
