### ISSUE TITLE
Icelandic holidays not available

### ISSUE THREAD

**Issue by albertospelta** [sql-bi/Bravo#718]
### Issue created from https://github.com/sql-bi/Bravo/issues/693#issuecomment-1701178640 originally posted by **@Eiriksra** ### 

I was very pleased with the news of Icelandic holidays being included, but when I updated Bravo and had a look, they were nowhere to be found. Any particular reason for this or was it just missed in the minor updates since then?

**Comment by albertospelta** [comment]
Fixed in version [1.0.6](https://github.com/sql-bi/Bravo/releases/tag/v1.0.6)

**Comment by Eiriksra** [comment]
You're the man Alberto. Thanks!

I feel a silly sense of pride that we have Icelandic holidays there.
Imagine how often Iceland, with its 400k inhabitants is ignored? But not in
Bravo - thanks to you!

R.
