### ISSUE TITLE
MTD and Max Month do now return correct values.

### ISSUE THREAD

**Issue by CapCityHyde** [sql-bi/Bravo#729]
### Describe the problem

I've been having this problem for a while. 

The MTD Time Intelligence measure do not return any value. 
A new measure of MaxM = MAX('Date'[Month]) does not return the proper month.
YTD and QTD Time Intelligence is fine.

I have a PBIX with sample sales date and a Bravo.BI calendar created. 
Any help would be appreciated. 

[CCPI Test MTD PBIX](https://drive.google.com/file/d/1osEULfQ88TaTgqk3fk65ABDQNyu0bgTy/view?usp=sharing)

### Bravo version

1.0.5 (1.0.8623.25801)

### Tabular model

Power BI Desktop, import mode

### Power BI

Desktop Version: 2.121.942.0 64-bit (September 2023)

**Comment by marcosqlbi** [comment]
In the repro, the last date with transactions is October 2, 2023. This means that MTD will work when you select October 2023 as a filter. The notion of MTD/QTD/YTD is always compared to the current filter context. See the descriptions here: https://www.daxpatterns.com/standard-time-related-calculations/
If you want a MTD/QTD/YTD for the last month/quarter/year available, you should create a custom template.

**Comment by CapCityHyde** [comment]
And MaxM = MAX('Date'[Month]) but returns the previous month? This should return October as the Max Month in the dataset. Correct?

**Comment by marcosqlbi** [comment]
I'm not sure I understand the question.
MTD/QTD/YTD are aggregation functions that work relatively to the current filter context.
If you do not include any date group/filter in your report, then they consider the last date in the Date table, not the last date with data.
If you want to create a selection for the last date with data, create an additional calculated column, such as

CurrentDate =
VAR LastDateWithData = CALCULATE ( MAX ( 'Date'[Date] ), 'Date'[ShowValueForDates] = TRUE )
RETURN IF ( LastDateWithData == 'Date'[Date], "LastDayWithData" )

Then, in the report create a filter where CurrentDate is LastDayWithData in the filter pane, at the report or page level, depending on how you want to structure your report. At that point, the measures in the template will behave as you expect without any date selected.

Please, download the sample files of the patterns on https://www.daxpatterns.com to see examples of how these functions work.
