### ISSUE TITLE
Export file - not enough memory error

### ISSUE THREAD

**Issue by uemgrobson** [sql-bi/Bravo#758]
### Describe the problem

Erro 700: Algo correu mal na exportação de dados. Por favor, tente de novo.
There's not enough memory to complete this operation. Please try again later when there may be more memory available.
![image](https://github.com/sql-bi/Bravo/assets/2350165/ef009eb1-03ab-47ee-843a-64bffc0ce205)

### Bravo version

1.0.6 (1.0.8693.18732)

### Tabular model

Power BI Desktop, import mode

### Power BI

problem to save file

### Anything else ?

Id de Rastreio: 00-ba4923ecab801c04e142e384abba6f3e-7fb1398f0e7c0d17-00

**Comment by albertospelta** [comment]
@uemgrobson could you please confirm whether you are using PBIDesktop in 32-bit or 64-bit mode ? 
You can find this information in the "About" panel of the application. 
![image](https://github.com/sql-bi/Bravo/assets/1957788/c1f22543-53a6-44a3-b73e-e32665c516ec)

**Comment by albertospelta** [comment]
Linking related issues https://github.com/sql-bi/Bravo/issues/629 https://github.com/sql-bi/Bravo/issues/596

**Comment by albertospelta** [comment]
Fixed in version [1.0.7](https://github.com/sql-bi/Bravo/releases/tag/v1.0.7)
