### ISSUE TITLE
Unable to update a date table defined by another user's template

### ISSUE THREAD

**Issue by preston-reynolds** [sql-bi/Bravo#764]
### Describe the problem

Here's the scenario I'm running into:
- Another team member created a .pbix
- They used a custom template in Bravo to generate the date table
- The custom template is linked to a Shared OneDrive file where the rest of the team has access
- Another team member attempts to update the Date Table using Bravo and receives this error: 

`Error HTTP/500: Internal Server Error.
Could not find a part of the path 'C:\Users\<USERNAME>\<COMPANY NAME>\Business Intelligence Agency - Documents\Internal Reports\Date Table Templates\BIA\dist\BIA.package.json'.
Trace Id: 00-81e73c083dd9d083986cd6c080567cb2-8bc06fc0cab15a88-00
Version: 1.0.6 (1.0.8693.18732)`

- Once this error show up, it becomes impossible to update the location of the template to a path that contains the new user's username.

The issue here is that once a custom template is used, unless the template resides in the exact same location for the user, (this really becomes a problem when the user is different from the original user), you are unable to update/select a date table definition template.

### Bravo version

1.0.6 (1.0.8693.18732)

### Tabular model

Power BI Desktop, import mode

### Power BI

2.124.1805.0 64-bit (December 2023)

### Anything else ?

Trace Id: 00-81e73c083dd9d083986cd6c080567cb2-8bc06fc0cab15a88-00

**Comment by albertospelta** [comment]
@preston-reynolds We have a fix for this issue that will be available in the next version, set to be released in a few days. If you'd like to test it, you can get the latest internal build by changing the update channel from `stable` to `dev` in the Options\About panel and following the link to download the installer.

This update allows the override of the template path applied by the original user by specifying an alternative path to use. After installing the version containing this fix, it should be enough to add your custom template to the list of templates within the Options\Templates panel. Then, through the `Browse...` button, you can then specify the effective path to use.

We will release the new version next week. In the meantime, if you could try out the internal/dev build and let us know if it resolves the issue, it would be greatly appreciated.

**Comment by albertospelta** [comment]
Fixed in version [1.0.7](https://github.com/sql-bi/Bravo/releases/tag/v1.0.7)
