### ISSUE TITLE
Can't get preview to populate in Visual Studio Code

### ISSUE THREAD

**Issue by Hiaasen290** [sql-bi/Bravo#766]
### Describe the problem

Trying to create a custom holiday definition table. When trying to connect/preview my data model I get the following message: 

"Bravo for Power BI is not running or not available on your system. Retry"

### Bravo version

1.0.7 (1.0.8809.14394)

### Tabular model

Power BI Desktop, import mode

### Power BI

Version: 2.126.927.0 64-bit (February 2024)

### Steps to reproduce the behavior

1. I'm able to choose my PBIX from the dropdown
2. Studio Code acts like it's generating a preview for about 30 seconds
3. Then this message pops up: "Bravo for Power BI is not running or not available on your system. Retry"

### Screenshots

![Bravo Error 1](https://github.com/sql-bi/Bravo/assets/161408991/8058db59-6fe4-4180-abac-00d437fe8036)
![Bravo Error 2](https://github.com/sql-bi/Bravo/assets/161408991/9ab02c2a-cb25-4135-9da6-068e2b3e1535)
![Bravo Error 3](https://github.com/sql-bi/Bravo/assets/161408991/e4e26067-93f0-4d0e-b9f4-f596c1311175)

**Comment by albertospelta** [comment]
Hi @Hiaasen290, 

When the error message appears in VSCode:
- did you see any related error messages in the Bravo application?
- Is Bravo still running on your system, or has it crashed or been closed?

Could you enable verbose diagnostics in the Bravo options panel and let us know if any errors are displayed when you receive the error message in VSCode?

**Comment by Hiaasen290** [comment]
There were no related error messages in Bravo. It did not crash and nothing is displayed in Bravo's log pane.

![Bravo Error 4](https://github.com/sql-bi/Bravo/assets/161408991/cc85fb69-6b83-47e9-b283-edf89fa47b06)

I tried to make the intended edits. I am in the US. Trying to add the following holidays to the Holiday Definitions table):

-  an internal company holiday, "Go Day," on January 13
- "Mother's Day" on the 2nd Sunday of May
- "Father's Day" on the 3rd Sunday of June

I do get the following error in Bravo when trying to implement the template I save with my attempted edits:

{"name":"[HOST] BravoException","objects":["Sqlbi.Bravo.Infrastructure.BravoException: Query (394, 17) Wrong configuration in HolidaysDefinition\r\n ---> Microsoft.AnalysisServices.AdomdClient.AdomdErrorResponseException: Query (394, 17) Wrong configuration in HolidaysDefinition\r\n   at Microsoft.AnalysisServices.AdomdClient.XmlaClient.CheckForSoapFault(XmlReader reader, XmlaResult xmlaResult, Boolean throwIfError)\r\n   at Microsoft.AnalysisServices.AdomdClient.XmlaClient.CheckForError(XmlReader reader, XmlaResult xmlaResult, Boolean throwIfError)\r\n   at Microsoft.AnalysisServices.AdomdClient.XmlaClient.SendMessage(Boolean endReceivalIfException, Boolean readSession, Boolean readNamespaceCompatibility)\r\n   at Microsoft.AnalysisServices.AdomdClient.XmlaClient.ExecuteStatement(String statement, IDictionary connectionProperties, IDictionary commandProperties, IDataParameterCollection parameters, Boolean isMdx)\r\n   at Microsoft.AnalysisServices.AdomdClient.AdomdConnection.XmlaClientProvider.Microsoft.AnalysisServices.AdomdClient.IExecuteProvider.ExecuteTabular(CommandBehavior behavior, ICommandContentProvider contentProvider, AdomdPropertyCollection commandProperties, IDataParameterCollection parameters)\r\n   at Microsoft.AnalysisServices.AdomdClient.AdomdCommand.ExecuteReader(CommandBehavior behavior)\r\n   at Dax.Template.Model.ModelChanges.GetPreviewData(AdomdConnection connection, String tableExpression, Int32 previewRows, String queryTablesDefinition) in /_/src/Dax.Template/Model/ModelChanges.cs:line 259\r\n   at Dax.Template.Model.ModelChanges.PopulatePreview(AdomdConnection connection, Model model, Int32 previewRows, CancellationToken cancellationToken) in /_/src/Dax.Template/Model/ModelChanges.cs:line 372\r\n   at Sqlbi.Bravo.Infrastructure.Services.DaxTemplate.DaxTemplateManager.GetPreviewChanges(Package package, Int32 previewRows, TabularConnectionWrapper connection, CancellationToken cancellationToken) in D:\\a\\1\\s\\src\\Infrastructure\\Services\\DaxTemplate\\DaxTemplateManager.cs:line 112\r\n   at Sqlbi.Bravo.Infrastructure.Services.DaxTemplate.DaxTemplateManager.GetPreviewChanges(DateConfiguration configuration, Int32 previewRows, TabularConnectionWrapper connection, CancellationToken cancellationToken) in D:\\a\\1\\s\\src\\Infrastructure\\Services\\DaxTemplate\\DaxTemplateManager.cs:line 87\r\n   at Sqlbi.Bravo.Services.ManageDatesService.GetPreviewChanges(PBIDesktopReport report, PreviewChangesSettings settings, CancellationToken cancellationToken) in D:\\a\\1\\s\\src\\Services\\ManageDatesService.cs:line 78\r\n   --- End of inner exception stack trace ---\r\n   at Sqlbi.Bravo.Services.ManageDatesService.GetPreviewChanges(PBIDesktopReport report, PreviewChangesSettings settings, CancellationToken cancellationToken) in D:\\a\\1\\s\\src\\Services\\ManageDatesService.cs:line 83\r\n   at lambda_method30(Closure , Object , Object[] )\r\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.SyncActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)\r\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeActionMethodAsync()\r\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)\r\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeNextActionFilterAsync()\r\n--- End of stack trace from previous location ---\r\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)\r\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)\r\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()\r\n--- End of stack trace from previous location ---\r\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)\r\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)\r\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)\r\n   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)\r\n   at Microsoft.AspNetCore.Authorization.Policy.AuthorizationMiddlewareResultHandler.HandleAsync(RequestDelegate next, HttpContext context, AuthorizationPolicy policy, PolicyAuthorizationResult authorizeResult)\r\n   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)\r\n   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)\r\n   at Hellang.Middleware.ProblemDetails.ProblemDetailsMiddleware.Invoke(HttpContext context)"],"time":1709149862436}

**Comment by albertospelta** [comment]
@Hiaasen290 Thank you for providing us with the error details. It appears that there might be a bug related to the error message display in VSCode. However, the root cause of the issue seems to be an incorrect configuration of `HolidaysDefinition` as indicated by the error you've reported.

> Query (394, 17) Wrong configuration in HolidaysDefinition

To better assist you and investigate the problem, could you please provide us with the `HolidaysDefinition.json` file that you have modified to include custom holidays? You can share the file directly here or email it to alberto.spelta@sqlbi.com if you prefer not to share it publicly on GitHub.

**Comment by Hiaasen290** [comment]
Hi Alberto,

Sorry for the delay, I got bogged down in other projects. Here's the .json file you asked for. Thanks very much for your help

[HolidaysDefinition.json](https://github.com/sql-bi/Bravo/files/14747381/HolidaysDefinition.json)

**Comment by albertospelta** [comment]
@Hiaasen290 thank you for sharing the file. We have been able to reproduce the error and will update you as soon as we have identified the issue.

**Comment by albertospelta** [comment]
We have identified the issue, and the fix is available in version [1.0.8](https://github.com/sql-bi/Bravo/releases/tag/v1.0.8)
