### ISSUE TITLE
Format DAX fails to synchronize - TypeError: Cannot read properties of undefined (reading 'match')

### ISSUE THREAD

**Issue by mscottsewell** [sql-bi/Bravo#778]
### Describe the problem

I inherited a pbix and wanted to use Format DAX to clean it up, but would only get the red wheel spinner, and no results.

When I clicked on the "Synchronize" button, it failed with a Whoops error. TypeError: Cannot read properties of undefined (reading 'match')

I tried a different pbix file and it worked fine - so it's something in this file that is causing an unhandled error. - Any suggestions on where I could look/replace/fix my file - or is there a setting that can help capture/avoid the error?

![image](https://github.com/sql-bi/Bravo/assets/6276300/629d140b-4088-482f-b0db-b331bb7e0b20)

### Bravo version

1.0.7 (1.0.8809.14394)

### Tabular model

Power BI Desktop, import mode

### Power BI

Desktop Version: 2.128.602.0 64-bit (April 2024)

### Steps to reproduce the behavior

1) go to Format DAX
2) Click on Synchronize
3) Receive Error.  (In this file, -but other files work fine.)

### Additional context

The other parts of Bravo seem to synch just fine. - only the 'Format DAX' feature is failing for this model.
I searched for "match" in the model, but haven't found anything with that name - not sure if that's relevant.

**Comment by albertospelta** [comment]
It's likely a bug in Bravo's UI JavaScript code. The error message and the "match" property may suggest this type of issue. Unfortunately, identifying the exact cause of the error is challenging without the ability to debug, but it could be related to a property having a null value. Would it be possible for you to share a copy of the PBIX file (saved as PBIT to remove the data)? Alternatively, to minimize the information shared, you could gradually remove tables and measures from the model until identifying which one causes the error, and then send us the file with only the measure that generates the error. If you prefer, you can send it directly to me at alberto.spelta@sqlbi.com without sharing it here on GitHub.

**Comment by mscottsewell** [comment]
Will do - this is an inherited file, so there's no assumptions as to what you might find. 😉 Thank you!

**Comment by albertospelta** [comment]
@mscottsewell We've identified the error and are currently fixing it. Meanwhile, as a workaround, you can format measures by setting a separator (`Formatting\Separators`) in the Bravo options panel. Choose any option except `Auto`, and be sure to exclude any measures highlighted in red from the formatting selection list.

**Comment by mscottsewell** [comment]
That workaround worked perfectly. Thank you!

**Comment by albertospelta** [comment]
Fixed in version [1.0.8](https://github.com/sql-bi/Bravo/releases/tag/v1.0.8)
