### ISSUE TITLE
Issue with exporting big fact table - how to activate Zip64 option

### ISSUE THREAD

**Issue by FrankG1965** [sql-bi/Bravo#796]
### Describe the problem

Error 700: Something wrong happened while exporting data. Please try again.
Attempted to write a stream that is larger than 4GiB without setting the zip64 option

### Bravo version

1.0.8 (1.0.8868.14547)

### Tabular model

Power BI Desktop, import mode

### Power BI

PBI June2024

### Additional context

Trying to export big file. After 75% progress the error messages comes. 
How can I activate the zip64 Option?

### Screenshots

![image](https://github.com/sql-bi/Bravo/assets/162360703/2033cd71-2da8-44d5-a72b-b3043e865330)

### Anything else ?

Trace Id: 00-7de9504e928c9d00ae45e9cffb124665-472cb8866555dbf8-00

**Comment by albertospelta** [comment]
@FrankG1965, the Zip64 option is internal and not configurable in the current version. However, we have released an update that allows enabling this option by holding down the `CTRL` key while clicking the `Export Selected` button.

When enabled, the diagnostic log panel displays the `Experimental feature: useZip64 is enabled` message as shown below.

![image](https://github.com/sql-bi/Bravo/assets/1957788/83ac2654-f32c-4840-8126-03efbff4243c)

This feature is available in the latest internal build and will be included in the next public release. To access the latest internal build, switch the update channel from `Stable` to `Dev` in the `Options/About` panel, and follow the provided link to download the installer.

Could you please test it and let us know if it works as expected?

> [!WARNING]
> Please note that this feature is experimental and disabled by default because, in some cases, it may generate invalid XLSX files that might not open correctly in Excel or LibreOffice. Due to this, and to avoid hitting the fixed 1 million rows per worksheet limit in Excel, we recommend using CSV instead of Excel spreadsheets for exporting large volumes of data.

**Comment by albertospelta** [comment]
@FrankG1965 This functionality has been released in version [1.0.9](https://github.com/sql-bi/Bravo/releases/tag/v1.0.9). I am closing this issue, but feel free to reopen it if you encounter further issues or have additional questions. Thanks!

**Comment by Aksana92** [comment]
Saudações 


Eu fiz a instalação do software Bravo for power bi V1.0.9 , mas as funcionalidades  como " exportar dados" não funcionam.

Pode me ajudar a encontrar uma solução

Grata.

**Comment by albertospelta** [comment]
@Aksana92 Could you please provide more details about the issue you're experiencing? For instance, are you encountering any error messages? Are you trying to export data from Power BI Desktop or from a semantic model in Power BI Service? Additionally, are you attempting to export the data to Excel or CSV?

Since this issue originally involved exporting a large table to Excel, if your situation is different, it would be best to create a new issue so we can track it appropriately. Thanks!
